from pathlib import Path
import re

def read(path): return Path(path).read_text(encoding='utf-8')
def write(path, text): Path(path).write_text(text, encoding='utf-8')
def sub_once(path, pattern, repl, flags=0):
    s=read(path); out,n=re.subn(pattern,repl,s,count=1,flags=flags)
    if n!=1: raise SystemExit(f'Expected one replacement in {path}, got {n}: {pattern[:80]}')
    write(path,out)
def replace_once(path, old, new):
    s=read(path); n=s.count(old)
    if n!=1: raise SystemExit(f'Expected one literal in {path}, got {n}: {old[:80]}')
    write(path,s.replace(old,new,1))

engine='src/engine.js'
sub_once(engine,r"function score\(p,o,weights\)\{.*?\nfunction ranking",'''function normalizedCriterion(c,x){return c.polarity==='cost'?100-x:x;}\nfunction score(p,o,weights){const wi=weightInfo(p);if(!wi.valid&&!weights)return {value:null,low:null,high:null,coverage:0,reason:'weights'};if(weights){const ws=p.criteria.map(c=>weights[c.id]);if(!ws.every(w=>num(w)&&w>=0&&w<=100)||Math.abs(ws.reduce((a,b)=>a+b,0)-100)>1e-6)return {value:null,low:null,high:null,coverage:0,reason:'weights'};}let low=0,missing=0,coverage=0;for(const c of p.criteria){const w=weights?weights[c.id]:c.weight;const x=o.scores[c.id]?.value;if(num(x)&&x>=0&&x<=100){low+=w*normalizedCriterion(c,x)/100;coverage+=w;}else missing+=w;}return {value:missing>1e-8?null:low,low,high:low+missing,coverage,reason:missing?'incomplete':''};}\nfunction ranking''',re.S)
sub_once(engine,r"function sensitivity\(p\)\{.*?\nfunction historySummary",'''function sensitivity(p){if(!weightInfo(p).valid)return {base:[],trials:[],switches:0};const base=ranking(p);if(base.length<2)return {base,trials:[],switches:0};const top=r=>r.length?r.filter(x=>Math.abs(x.value-r[0].value)<1e-7).map(x=>x.id).sort().join(','):'';let trials=[];for(const c of p.criteria){for(const delta of [-5,5]){const nw=c.weight+delta,remaining=100-c.weight;if(nw<0||nw>100||remaining<=0)continue;const w={};for(const k of p.criteria)w[k.id]=k.id===c.id?nw:k.weight*(100-nw)/remaining;const r=ranking(p,w);if(!r.length)continue;trials.push({criterion:c.name,delta,top:r.filter(x=>Math.abs(x.value-r[0].value)<1e-7).map(x=>x.title),changed:top(r)!==top(base)});}}return {base,trials,switches:trials.filter(t=>t.changed).length};}\nfunction rankingAt(p,criterionId,w){const c=p.criteria.find(x=>x.id===criterionId);if(!c||!num(w)||w<0||w>100)return [];const others=p.criteria.filter(k=>k.id!==criterionId),baseOther=others.reduce((a,k)=>a+k.weight,0),weights={};weights[criterionId]=w;if(!others.length)return ranking(p,weights);if(baseOther<=0){const each=(100-w)/others.length;for(const k of others)weights[k.id]=each;}else for(const k of others)weights[k.id]=k.weight*(100-w)/baseOther;return ranking(p,weights);}\nfunction topKey(r){return r.length?r.filter(x=>Math.abs(x.value-r[0].value)<1e-7).map(x=>x.id).sort().join(','):'';}\nfunction breakEven(p){const base=ranking(p);if(base.length<2||!weightInfo(p).valid)return [];const baseTop=topKey(base);return p.criteria.map(c=>{let best=null;for(let n=1;n<200;n++){const w=n/2;if(w<=0||w>=100)continue;const r=rankingAt(p,c.id,w);if(!r.length||topKey(r)===baseTop)continue;const d=Math.abs(w-c.weight);if(!best||d<best.distance)best={criterionId:c.id,criterion:c.name,current:c.weight,threshold:w,distance:d,newTop:r[0].title};}return best||{criterionId:c.id,criterion:c.name,current:c.weight,threshold:null,distance:null,newTop:null};});}\nfunction historySummary''',re.S)
replace_once(engine,'function check(p){',"function authorityIssues(p){const selectedSet=new Set(selected(p).map(o=>o.id)),out=[];for(const e of p.enablers){if(!selectedSet.has(e.optionId))continue;if(e.control==='unknown')out.push({section:'enablers',level:'missing',code:'authorityIssueUnknownControl',entity:e.id,title:e.title||''});if(e.status==='unknown')out.push({section:'enablers',level:'missing',code:'authorityIssueUnknownStatus',entity:e.id,title:e.title||''});if(e.status==='pending')out.push({section:'enablers',level:'warning',code:'authorityIssuePending',entity:e.id,title:e.title||''});if(e.status==='blocked')out.push({section:'enablers',level:'blocking',code:'authorityIssueBlocked',entity:e.id,title:e.title||''});}return out;}\nfunction check(p){")
replace_once(engine," for(const e of p.enablers){if(!optIds.has(e.optionId))add('enablers','blocking',T('s058')+(e.title||''),e.id);if(!text(e.owner)||!text(e.source)||!text(e.route))add('enablers','missing',T('s059')+(e.title||''),e.id);if(e.control!=='internal'&&!text(e.fallback))add('enablers','missing',T('s060')+e.title,e.id);}\n", " for(const e of p.enablers){if(!optIds.has(e.optionId))add('enablers','blocking',T('s058')+(e.title||''),e.id);if(!text(e.owner)||!text(e.source)||!text(e.route))add('enablers','missing',T('s059')+(e.title||''),e.id);if(e.control!=='internal'&&!text(e.fallback))add('enablers','missing',T('s060')+e.title,e.id);}\n for(const issue of authorityIssues(p))add(issue.section,issue.level,T(issue.code)+(issue.title||T('s395')),issue.entity);\n")
replace_once(engine,'const api={SCHEMA,clone,num,text,uid,years,blank,option,reference,transition,enabler,initiative,weightInfo,score,ranking,sensitivity,historySummary,progress,selected,selectedInitiatives,budgetSummary,cycles,check,syncYears,validateImport,demo};','const api={SCHEMA,clone,num,text,uid,years,blank,option,reference,transition,enabler,initiative,weightInfo,score,ranking,sensitivity,breakEven,rankingAt,authorityIssues,historySummary,progress,selected,selectedInitiatives,budgetSummary,cycles,check,syncYears,validateImport,demo};')

for path,vals in [('src/locales/en.js',{'authorityIssueUnknownControl':'Authority owner/control is unknown: ','authorityIssueUnknownStatus':'Authority status is unknown: ','authorityIssuePending':'Authority decision is pending: ','authorityIssueBlocked':'Authority decision is blocked: '}),('src/locales/ar.js',{'authorityIssueUnknownControl':'مالك الصلاحية أو نطاقها غير معروف: ','authorityIssueUnknownStatus':'حالة قرار الصلاحية غير معروفة: ','authorityIssuePending':'قرار الصلاحية معلّق: ','authorityIssueBlocked':'قرار الصلاحية متعثر: '})]:
    s=read(path)
    if '"authorityIssueUnknownControl"' not in s:
        marker='const messages={\n'; block=''.join('  '+repr(k)+': '+repr(v)+',\n' for k,v in vals.items()).replace("'",'"'); s=s.replace(marker,marker+block,1)
    write(path,s)

cp='src/criteria-polarity.js'
sub_once(cp,r"function normalized\(c,x\).*?E\.score=score;E\.ranking=ranking;E\.sensitivity=sensitivity;\n",'',re.S)
sub_once(cp,r"document\.addEventListener\('change',e=>\{const s=e\.target\.closest\('\[data-polarity\]'\);.*?\}\);","document.addEventListener('change',e=>{const s=e.target.closest('[data-polarity]');if(!s||!root.SultanApp)return;const p=root.SultanApp.getProject(),c=p.criteria[Number(s.dataset.polarity)];if(!c)return;const before=c.polarity||'benefit';if(s.value!==before&&!confirm(T('polarityAnchorWarning'))){s.value=before;return;}c.polarity=s.value;root.SultanApp.setProject(p);root.SultanApp.navigate('priorities');});",re.S)

for path in ('src/locales/en.js','src/locales/ar.js'):
    s=read(path)
    for n,name in enumerate(['identity','mandates','choices','references','transitions','enablers','initiatives','issues','review'],1): s=s.replace(f'<h2>{n}.',f'<h2 data-report-section="{name}">{n}.',1)
    write(path,s)

loc='src/locales/execution-upgrades.js';s=read(loc)
en_old="  exportNeedsWork:'Add project content before exporting a strategy.'\n"
en_new="""  exportNeedsWork:'Add project content before exporting a strategy.',
  breakEvenNoSwitch:'No switch within the meaningful 0.5–99.5% range.',unplottedAuthority:'Not plotted — authority data is insufficient',unestimatedYears:'(+ %{0} unestimated year(s))',currencySAR:'SAR',
  polarityAnchorWarning:'Changing criterion direction reverses the meaning of the scale. Review and rewrite the 0 and 100 anchors before relying on the ranking. Continue?',
  externalEscalations:'External / shared decisions requiring action',internalPendingDecisions:'Internal decisions still unresolved',affectedWork:'Affected initiative / start year',
  gregorianLabel:'Gregorian',hijriLabel:'Hijri',preparedBy:'Prepared by',generatedOn:'Generated on',exportMenu:'Export',projectDataExport:'Reusable project JSON',strategyDraftExport:'Strategy draft',leadershipExport:'Leadership report',internalExport:'Internal report',escalationExport:'Escalation pack',sectionFileExport:'Section file'
"""
ar_old="  exportNeedsWork:'أضف محتوى للمشروع قبل تصدير الاستراتيجية.'\n"
ar_new="""  exportNeedsWork:'أضف محتوى للمشروع قبل تصدير الاستراتيجية.',
  breakEvenNoSwitch:'لا يوجد انقلاب ضمن المدى ذي المعنى 0.5–99.5٪.',unplottedAuthority:'غير مرسوم — بيانات الصلاحية غير كافية',unestimatedYears:'(+ %{0} سنة/سنوات غير مقدّرة)',currencySAR:'ريال',
  polarityAnchorWarning:'تغيير اتجاه المعيار يعكس معنى المقياس. راجع وأعد صياغة مرساتي 0 و100 قبل الاعتماد على الترتيب. هل تريد المتابعة؟',
  externalEscalations:'قرارات خارجية / مشتركة تتطلب إجراء',internalPendingDecisions:'قرارات داخلية لم تُحسم بعد',affectedWork:'المبادرة / سنة البدء المتأثرة',
  gregorianLabel:'ميلادي',hijriLabel:'هجري',preparedBy:'أُعد بواسطة',generatedOn:'تاريخ الإنشاء',exportMenu:'تصدير',projectDataExport:'ملف مشروع قابل للاستكمال',strategyDraftExport:'مسودة الاستراتيجية',leadershipExport:'تقرير القيادة',internalExport:'التقرير الداخلي',escalationExport:'حزمة التصعيد',sectionFileExport:'ملف القسم'
"""
if en_old not in s or ar_old not in s: raise SystemExit('Localization insertion anchors not found')
s=s.replace(en_old,en_new,1).replace(ar_old,ar_new,1);write(loc,s)

ex='src/execution-upgrades.js';s=read(ex)
s=re.sub(r"const baseCheck=E\.check\.bind\(E\);.*?return out;\};\n\n",'',s,count=1,flags=re.S)
s=re.sub(r"function rankingAt\(p,criterionId,w\).*?E\.breakEven=breakEven;\n\n",'',s,count=1,flags=re.S)
s=s.replace('<h2>Authority Space</h2>',"<h2>${esc(T('authoritySpaceTitle'))}</h2>")
s,n=re.subn(r"function escalationHtml\(p\)\{.*?\nfunction dualDate",'''function affectedWork(p,enablerId){return p.initiatives.filter(i=>(i.enablerIds||[]).includes(enablerId)).map(i=>(i.title||T('s412'))+' · '+i.startYear).join('; ')||'—';}
function escalationTable(p,items){return items.length?`<table><thead><tr><th>${esc(T('authorityChoice'))}</th><th>${esc(T('s492'))}</th><th>${esc(T('s495'))}</th><th>${esc(T('escalationDue'))}</th><th>${esc(T('affectedWork'))}</th><th>${esc(T('escalationRoute'))}</th><th>${esc(T('escalationFallback'))}</th></tr></thead><tbody>${items.map(x=>`<tr><td>${esc(x.choice)}</td><td>${esc(x.title)}</td><td>${esc(x.owner||T('s408'))}</td><td>${x.dueYear??'—'}</td><td>${esc(affectedWork(p,x.id))}</td><td>${esc(x.route||T('s408'))}</td><td>${esc(x.fallback||T('s408'))}</td></tr>`).join('')}</tbody></table>`:`<p>${esc(T('escalationEmpty'))}</p>`;}
function escalationHtml(p){const selected=new Set(p.options.filter(o=>o.decision==='select').map(o=>o.id)),external=E.authorityEscalationItems(p),internal=p.enablers.filter(e=>selected.has(e.optionId)&&e.control==='internal'&&e.status!=='ready').map(e=>({id:e.id,optionId:e.optionId,choice:p.options.find(o=>o.id===e.optionId)?.title||'',title:e.title||'',owner:e.owner||'',dueYear:e.dueYear,route:e.route||'',fallback:e.fallback||''})).sort((a,b)=>(a.dueYear??9999)-(b.dueYear??9999));return `<section class="report-extra escalation-report"><h2>${esc(T('escalationPack'))}</h2><p><b>${esc(p.institution.name||T('s250'))}</b> · ${esc(T('generatedOn'))}: ${esc(dualDate())} · revision ${p.revision}</p><p>${esc(T('escalationPackIntro'))}</p><h3>${esc(T('externalEscalations'))}</h3>${escalationTable(p,external)}<h3>${esc(T('internalPendingDecisions'))}</h3>${escalationTable(p,internal)}</section>`;}
function dualDate''',s,count=1,flags=re.S)
if n!=1: raise SystemExit('Escalation replacement failed')
s,n=re.subn(r"function dualDate\(\)\{.*?\nfunction fullDocument",'''function dualDate(){const d=new Date(),greg=new Intl.DateTimeFormat(SultanI18n.language==='ar'?'ar-SA-u-ca-gregory':'en-GB',{dateStyle:'medium'}).format(d),hijri=new Intl.DateTimeFormat('ar-SA-u-ca-islamic',{dateStyle:'medium'}).format(d);return `${T('gregorianLabel')}: ${greg} · ${T('hijriLabel')}: ${hijri}`;}
function leadershipBody(body){const doc=new DOMParser().parseFromString(body,'text/html'),h=doc.querySelector('[data-report-section="issues"]');if(h){let n=h.nextSibling;while(n){const next=n.nextSibling;if(n.nodeType===1&&n.matches&&n.matches('h2[data-report-section]'))break;n.remove();n=next;}h.remove();}let k=0;doc.querySelectorAll('h2[data-report-section]').forEach(x=>{k++;x.innerHTML=x.innerHTML.replace(/^\s*\d+\.\s*/,k+'. ');});return doc.body.innerHTML;}
function enhancedReport(p,leadership=false){let body=root.SultanApp.getReport();const stamp=`<p class="report-date">${esc(dualDate())}</p>`;body=body.replace(/(<header>[\s\S]*?<h1>[\s\S]*?<\/h1>)/,m=>m+stamp);body=body.replace('</article>',authorityHtml(p)+escalationHtml(p)+'</article>');return leadership?leadershipBody(body):body;}
function fullDocument''',s,count=1,flags=re.S)
if n!=1: raise SystemExit('Report replacement failed')
s=re.sub(r"document\.addEventListener\('click',e=>\{const b=e\.target\.closest\('\[data-action\]'\);if\(!b\|\|!root\.SultanApp\)return;const action=b\.dataset\.action;if\(!\['new','demo'\]\.includes\(action\)\)return;.*?\},true\);\n",'',s,count=1,flags=re.S)
s,n=re.subn(r"function renderProgress\(\)\{.*?\nfunction renderBreakEven",'''function renderProgress(){if(!root.SultanApp)return;const p=root.SultanApp.getProject(),nav=document.getElementById('navigation');if(nav){for(const btn of nav.querySelectorAll('[data-section]')){const key=btn.dataset.section;if(key==='home')continue;const n=sectionIssues(p,key);let badge=btn.querySelector('.exec-badge');if(!badge){badge=document.createElement('span');badge.className='exec-badge';btn.append(badge);}badge.textContent=n?String(n):'✓';badge.dataset.ok=n?'0':'1';}}
 const content=document.getElementById('content');if(!content||content.querySelector('.exec-toolbar')||['home','about'].includes(currentSection()))return;const bar=document.createElement('div');bar.className='exec-toolbar noPrint';if(currentSection()==='review'){const legacy=content.querySelector('.toolbar.noPrint');if(legacy)legacy.classList.add('legacy-export-toolbar');bar.innerHTML=`<span>${esc(T('executionProgress'))}</span><details class="export-menu"><summary class="btn primary small">${esc(T('exportMenu'))}</summary><div class="export-menu-panel"><button class="btn small" data-action="report">${esc(T('strategyDraftExport'))}</button><button class="btn small" data-exec="leadership-report">${esc(T('leadershipExport'))}</button><button class="btn small" data-exec="internal-report">${esc(T('internalExport'))}</button><button class="btn small" data-exec="escalation">${esc(T('escalationExport'))}</button><button class="btn small" data-action="project">${esc(T('projectDataExport'))}</button><button class="btn small" data-exec="section-export">${esc(T('sectionFileExport'))}</button><button class="btn small" data-action="print">${esc(T('s523'))}</button></div></details><button class="btn small" data-exec="section-import">${esc(T('sectionImport'))}</button>`;}else{bar.innerHTML=`<span>${esc(T('executionProgress'))}</span><button class="btn small" data-exec="section-export">${esc(T('sectionExport'))}</button><button class="btn small" data-exec="section-import">${esc(T('sectionImport'))}</button>${currentSection()==='enablers'?`<button class="btn primary small" data-exec="escalation">${esc(T('escalationPack'))}</button>`:''}`;}content.prepend(bar);}
function renderBreakEven''',s,count=1,flags=re.S)
if n!=1: raise SystemExit('Toolbar replacement failed')
s,n=re.subn(r"function renderBreakEven\(\)\{.*?\nfunction updateSensitivityPreview",'''function renderBreakEven(){if(currentSection()!=='priorities'||!root.SultanApp)return;const content=document.getElementById('content');if(!content||content.querySelector('.break-even-card'))return;const p=root.SultanApp.getProject(),rows=E.breakEven(p),card=document.createElement('article');card.className='card break-even-card';card.innerHTML=`<h2>${esc(T('breakEvenTitle'))}</h2><p class="muted">${esc(T('breakEvenIntro'))}</p>${rows.length?rows.map(r=>`<p><b>${esc(r.criterion)}</b>: ${r.threshold===null?esc(T('breakEvenNoSwitch')):`${fmt(r.current)}% → ${fmt(r.threshold)}% · ${esc(T('breakEvenSwitch'))}: ${esc(r.newTop)}`}</p>`).join(''):`<p>${esc(T('breakEvenNone'))}</p>`}<div class="sensitivity-lab"><h3>${esc(T('sensitivityLab'))}</h3><p class="muted">${esc(T('sensitivityLabHelp'))}</p>${p.criteria.map(c=>`<label class="sensitivity-row"><span>${esc(c.name)}</span><input type="range" min="0" max="100" step="1" value="${c.weight}" data-sensitivity="${esc(c.id)}"><output>${fmt(c.weight)}%</output></label>`).join('')}<div class="sensitivity-preview"></div></div>`;content.append(card);updateSensitivityPreview(card,p);}
function updateSensitivityPreview''',s,count=1,flags=re.S)
if n!=1: raise SystemExit('Break-even UI replacement failed')
write(ex,s)

write('src/review-visuals.js',r'''/* Executive review visuals that keep strategic value, authority and money separate. */
(function(root){
'use strict';
const E=root.Sultan,T=root.SultanI18n.t,esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>typeof n==='number'&&Number.isFinite(n)?Math.round(n).toLocaleString('en-US'):'—';
function choiceCost(p,id){const ins=p.initiatives.filter(i=>i.optionId===id);let total=0,unknown=0;for(const i of ins)for(const b of i.budget)if(b.year>=i.startYear&&b.year<=i.endYear){if(typeof b.amount==='number'&&Number.isFinite(b.amount))total+=b.amount;else unknown++;}const confirmed=ins.length>0&&ins.every(i=>i.budgetStatus==='confirmed');return {total,unknown,confirmed,count:ins.length};}
function render(){if(location.hash!=='#review'||!root.SultanApp)return;const content=document.getElementById('content');if(!content||content.querySelector('.portfolio-review'))return;const p=root.SultanApp.getProject(),selected=p.options.filter(o=>o.decision==='select'&&o.type!=='requirement'),authority=Object.fromEntries(E.authoritySpace(p).map(x=>[x.optionId,x])),rank=Object.fromEntries(E.ranking(p).map(x=>[x.id,x]));const card=document.createElement('article');card.className='card portfolio-review';const plotted=[],unplotted=[];selected.forEach((o,i)=>{const v=rank[o.id]?.value,a=authority[o.id]?.clearance;if(v==null||a==null)unplotted.push({o,i});else plotted.push({o,i,v,a});});const dots=plotted.map(({o,i,v,a})=>`<button type="button" class="matrix-dot" style="--x:${v};--y:${a}" title="${esc(o.title)} · ${Math.round(v)} / ${Math.round(a)}"><span>${i+1}</span></button>`).join('');const unknown=unplotted.length?`<div class="matrix-unplotted"><b>${esc(T('unplottedAuthority'))}</b>${unplotted.map(({o,i})=>`<span><b>${i+1}</b> ${esc(o.title)}</span>`).join('')}</div>`:'';card.innerHTML=`<h2>${esc(T('portfolioMatrix'))}</h2><p class="muted">${esc(T('portfolioMatrixHelp'))}</p><div class="matrix-wrap"><span class="matrix-y">${esc(T('authorityAxis'))}</span><div class="matrix"><i class="matrix-v"></i><i class="matrix-h"></i>${dots}</div><span class="matrix-x">${esc(T('strategicValue'))}</span></div>${unknown}<div class="matrix-legend">${selected.map((o,i)=>`<span><b>${i+1}</b> ${esc(o.title)}</span>`).join('')}</div><h2>${esc(T('valueFunding'))}</h2><div class="tablewrap"><table><thead><tr><th>${esc(T('authorityChoice'))}</th><th>${esc(T('strategicValue'))}</th><th>${esc(T('declaredInvestment'))}</th><th>${esc(T('fundingState'))}</th></tr></thead><tbody>${selected.map(o=>{const c=choiceCost(p,o.id),v=rank[o.id]?.value,amount=`${money(c.total)} ${esc(T('currencySAR'))}${c.unknown?` ${esc(T('unestimatedYears',[c.unknown]))}`:''}`;return `<tr><td>${esc(o.title)}</td><td>${v==null?'—':Math.round(v)}</td><td>${amount}</td><td>${esc(c.confirmed?T('fundingConfirmed'):T('fundingMixed'))}</td></tr>`;}).join('')}</tbody></table></div>`;const heading=content.querySelector('.heading');if(heading)heading.insertAdjacentElement('afterend',card);else content.prepend(card);}
document.addEventListener('sultan:render',()=>setTimeout(render,0));setTimeout(render,0);
})(globalThis);
''')

css='src/execution-upgrades.css';s=read(css)
s=s.replace('.matrix{position:relative;border:1px solid #cadad2;background:linear-gradient(90deg,#fafbf9 50%,#f2f7f2 50%),linear-gradient(#eef6ef 50%,transparent 50%);overflow:hidden}', '.matrix{position:relative;border:1px solid #cadad2;background:linear-gradient(90deg,#fafbf9 50%,#f2f7f2 50%),linear-gradient(#eef6ef 50%,transparent 50%);overflow:visible}')
s=s.replace('.matrix-dot{position:absolute;left:calc(var(--x)*1%);bottom:calc(var(--y)*1%);transform:translate(-50%,50%);width:30px;height:30px;', '.matrix-dot{position:absolute;inset-inline-start:clamp(15px,calc(var(--x)*1%),calc(100% - 15px));bottom:clamp(15px,calc(var(--y)*1%),calc(100% - 15px));transform:translate(-50%,50%);width:30px;height:30px;')
s+='\nhtml[dir="rtl"] .matrix-dot{transform:translate(50%,50%)}.matrix-unplotted{display:flex;gap:8px;flex-wrap:wrap;padding:10px 12px;border:1px dashed #c5a95d;border-radius:9px;margin:-6px 0 16px}.matrix-unplotted>b{width:100%}.matrix-unplotted span{font-size:12px}.legacy-export-toolbar{display:none!important}.export-menu{position:relative}.export-menu>summary{list-style:none;cursor:pointer}.export-menu>summary::-webkit-details-marker{display:none}.export-menu-panel{position:absolute;z-index:20;inset-inline-end:0;top:calc(100% + 6px);min-width:260px;padding:10px;display:grid;gap:7px;background:#fff;border:1px solid #dce7df;border-radius:10px;box-shadow:0 12px 30px #12363b22}.export-menu-panel .btn{text-align:start}\n'
write(css,s)

app='src/app.js';s=read(app)
s=s.replace("function replaceOK(){return !started||confirm(T('s549'));}","function replaceOK(){return !started||confirm(T('s549'));}\nfunction backupBeforeReplace(){if(started)download('SULTAN_Auto_Backup_Before_Replace.json',JSON.stringify(p,null,2),'application/json');}")
s=s.replace("case 'new':if(replaceOK()){p=E.blank();","case 'new':if(replaceOK()){backupBeforeReplace();p=E.blank();")
s=s.replace("case 'demo':if(replaceOK()){p=E.demo();","case 'demo':if(replaceOK()){backupBeforeReplace();p=E.demo();")
write(app,s)

write('tests/i18n.test.js',r'''/* Translation completeness and interpolation parity are release requirements. */
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const baseEn=require('../src/locales/en.js'),baseAr=require('../src/locales/ar.js');
const dictionaries={en:{...baseEn},ar:{...baseAr}},context={globalThis:{SultanLocales:dictionaries}};vm.createContext(context);
for(const file of fs.readdirSync(path.join(__dirname,'../src/locales')).filter(x=>x.endsWith('.js')&&!['en.js','ar.js'].includes(x)).sort())vm.runInContext(fs.readFileSync(path.join(__dirname,'../src/locales',file),'utf8'),context,{filename:file});
const en=context.globalThis.SultanLocales.en,ar=context.globalThis.SultanLocales.ar;assert.deepEqual(Object.keys(en).sort(),Object.keys(ar).sort());
for(const key of Object.keys(en)){assert.equal(typeof en[key],'string');assert.equal(typeof ar[key],'string');const vars=s=>[...s.matchAll(/%\{\d+\}/g)].map(x=>x[0]).sort();assert.deepEqual(vars(en[key]),vars(ar[key]),'Placeholder mismatch: '+key);}
console.log(JSON.stringify({translationKeys:Object.keys(en).length,localeFiles:fs.readdirSync(path.join(__dirname,'../src/locales')).filter(x=>x.endsWith('.js')).length,parity:'pass'}));
''')
write('tests/hardening071.test.js',r'''/* Regression coverage for 0.7.1 hardening. */
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),E=require('../src/engine.js');
let p=E.blank();p.criteria=[{id:'benefit',name:'Benefit',weight:50,low:'low',high:'high',polarity:'benefit'},{id:'cost',name:'Cost',weight:50,low:'low',high:'high',polarity:'cost'}];let a=E.option(),b=E.option();a.id='a';a.title='A';a.scores={benefit:{value:80,note:'x'},cost:{value:20,note:'x'}};b.id='b';b.title='B';b.scores={benefit:{value:70,note:'x'},cost:{value:60,note:'x'}};p.options=[a,b];assert.ok(E.score(p,a).value>E.score(p,b).value);const sw=E.breakEven(p);assert.equal(sw.length,2);for(const x of sw)assert.ok(x.threshold===null||(x.threshold>0&&x.threshold<100));p=E.demo();const ai=E.authorityIssues(p);assert.ok(ai.some(x=>x.entity==='e1'&&x.code==='authorityIssuePending'));assert.ok(ai.some(x=>x.entity==='e2'&&x.code==='authorityIssueUnknownControl'));const checked=E.check(p);assert.ok(checked.some(x=>x.entity==='e1'&&x.section==='enablers'));assert.ok(checked.some(x=>x.entity==='e2'&&x.section==='enablers'));
const ex=fs.readFileSync('src/execution-upgrades.js','utf8'),rv=fs.readFileSync('src/review-visuals.js','utf8'),css=fs.readFileSync('src/execution-upgrades.css','utf8'),cp=fs.readFileSync('src/criteria-polarity.js','utf8');assert.match(ex,/T\('authoritySpaceTitle'\)/);assert.doesNotMatch(ex,/Draft based on user inputs\[\^<\]/);assert.match(ex,/data-report-section="issues"/);assert.match(rv,/matrix-unplotted/);assert.match(rv,/unestimatedYears/);assert.match(css,/inset-inline-start/);assert.match(css,/html\[dir="rtl"\] \.matrix-dot/);assert.doesNotMatch(cp,/E\.score=score/);assert.match(cp,/polarityAnchorWarning/);console.log(JSON.stringify({hardening071:'pass',checks:14}));
''')

ci=Path('.github/workflows/ci.yml')
if ci.exists():
    s=read(ci)
    if 'node tests/hardening071.test.js' not in s:
        anchor='node tests/i18n.test.js'
        if anchor not in s: raise SystemExit('CI i18n anchor missing')
        s=s.replace(anchor,anchor+'\n          node tests/hardening071.test.js',1);write(ci,s)

s=read('build.py').replace("VERSION='0.7.0'","VERSION='0.7.1'");write('build.py',s)
s=read('CHANGELOG.md')
if '## 0.7.1' not in s:s=s.replace('# Changelog\n','# Changelog\n\n## 0.7.1 — Hardening\n\n- Fix bilingual report dates, leadership numbering, Authority Space localization, RTL matrix geometry, unknown-authority visibility, meaningful switch-point reporting, unknown budget visibility, escalation-pack identity/scope, criterion-polarity warnings, and destructive-backup timing.\n- Move polarity, switch points, and authority issue semantics into the deterministic engine and expand locale/regression coverage.\n- Consolidate overlapping review exports behind one export menu.\n',1)
write('CHANGELOG.md',s)
