'use strict';
const assert=require('node:assert/strict');
global.SultanLocales={en:require('../src/locales/en.js'),ar:require('../src/locales/ar.js')};for(const f of ['final','guided','field-guide','lens','strategy','council','market'])require('../src/locales/'+f+'.js');global.SultanI18n=require('../src/i18n.js');global.Sultan=require('../src/import.js');for(const f of ['final-core','context-core','sector-library','draft-engine','expert-lens','strategy-core','goal-planner','share-codec','council-core','board-pack'])require('../src/'+f+'.js');const memory=new Map();global.localStorage={getItem:k=>memory.get(k)||null,setItem:(k,v)=>memory.set(k,v)};const E=Sultan,C=SultanCouncil,S=SultanShare;let count=0;async function test(name,fn){await fn();count++;console.log('PASS '+name);}
(async()=>{
await test('Old projects migrate without losing values',()=>{const p=E.demo();delete p.council;assert.deepEqual(E.validateImport(p).council,C.defaults());assert.deepEqual(E.validateImport(E.demo()).council,C.defaults());});
await test('Unknown credential fields and malformed shape rejected',()=>{const p=E.blank();p.council.apiKey='secret';assert.throws(()=>E.validateImport(p));p.council=C.defaults();p.council.requests={};assert.throws(()=>E.validateImport(p));});
await test('Shared snapshots exclude uploaded summaries and AI logs',()=>{const p=E.demo();p.context.documents.push({summary:'PRIVATE_DOC'});p.context.ai.log.push({model:'SECRET_LOG'});const s=JSON.stringify(C.snapshot(p));assert.ok(!s.includes('PRIVATE_DOC')&&!s.includes('SECRET_LOG')&&!s.includes('council'));});
await test('Three owners receive independent capabilities without project private keys',async()=>{const r=await C.createLinks(E.demo(),['A','B','C']);assert.equal(r.project.council.requests.length,3);assert.equal(new Set(r.packets.map(p=>p.replyKey.x)).size,3);assert.ok(!JSON.stringify(r.project).includes('privateKey'));assert.ok(!JSON.stringify(r.project).includes('replyKey'));assert.equal(r.packets[0].payload.isDemo,true);});
await test('Invalid owner count, duplicate names and expiry bounds rejected',async()=>{await assert.rejects(()=>C.createLinks(E.demo(),['A']));await assert.rejects(()=>C.createLinks(E.demo(),['A','a','C']));await assert.rejects(()=>C.createLinks(E.demo(),[],91));});
await test('Signed snapshots round trip and reject tampering',async()=>{const {packets:[p]}=await C.createLinks(E.demo(),[]);assert.equal((await S.read(await S.encode(p))).payload.kind,'read');p.payload.snapshot.institution.name='tamper';await assert.rejects(async()=>S.read(await S.encode(p)));});
await test('Expected invitation key and duplicate protection',async()=>{const r=await C.createLinks(E.demo(),['A','B','C']),response=await S.reply(r.packets[0],'changes','Verify baseline'),token=await S.encode(response),q=await C.accept(r.project,token);assert.equal(q.council.responses.length,1);assert.equal(await C.verifyResponse(q,q.council.responses[0]),true);assert.equal(q.reviewedRevision,r.project.reviewedRevision);await assert.rejects(()=>C.accept(q,token));await assert.rejects(()=>C.accept(E.demo(),token));});
await test('Substituted keys and edited saved response do not verify',async()=>{const r=await C.createLinks(E.demo(),['A','B','C']),bad=await S.reply(r.packets[1],'support','Support');bad.payload.requestId=r.packets[0].payload.id;await assert.rejects(async()=>C.accept(r.project,await S.encode(bad)));const good=await S.reply(r.packets[0],'support','Support'),q=await C.accept(r.project,await S.encode(good));q.council.responses[0].comment='tamper';assert.equal(await C.verifyResponse(q,q.council.responses[0]),false);});
await test('Expired invitation refuses new reply',async()=>{const r=await C.createLinks(E.demo(),['A','B','C']),p=r.packets[0];p.payload.expiresAt='2000-01-01T00:00:00Z';const signed=await S.sign(p.payload,await S.issuer());signed.replyKey=p.replyKey;await assert.rejects(()=>S.reply(signed,'support','Too late'));});
await test('Checkpoint comparison preserves zero and labels arbitrary fields',async()=>{let p=E.demo();const old=await C.basis(p);p=await C.checkpoint(p,{label:'Fictional pilot',nextDate:'2027-03-01',note:'Confirm baseline'});assert.equal(await C.basis(p),old);assert.equal(C.diff(p,p.council.checkpoints[0]).length,0);p.transitions[0].baseline=0;p.institution.mission='New mission';const d=C.diff(p,p.council.checkpoints[0]);assert.ok(d.some(x=>x.path.endsWith('.baseline')&&x.after===0));assert.ok(d.some(x=>x.path==='institution.mission'));assert.notEqual(await C.basis(p),old);assert.deepEqual(E.validateImport(p).council,p.council);});
await test('Calendar validity and twelve checkpoint bound',async()=>{await assert.rejects(()=>C.checkpoint(E.demo(),{label:'Review',nextDate:'2027-02-30'}));let p=E.demo();for(let i=0;i<14;i++)p=await C.checkpoint(p,{label:'Review '+i,nextDate:'2027-03-01'});assert.equal(p.council.checkpoints.length,12);});
await test('Adversary never changes unknowns scores or approval checks',()=>{const p=E.demo(),before=JSON.stringify(p),issues=E.check(p);assert.ok(C.adversary(p).findings.length);assert.equal(JSON.stringify(p),before);assert.deepEqual(E.check(p),issues);});
await test('Relative ten percent weight changes are exact',()=>{const p=E.demo(),s=C.stress(p);assert.ok(s.available);for(const t of s.trials)assert.ok(Math.abs(t.to-t.from*(1+t.delta/100))<1e-7);});
await test('Incomplete comparisons never claim robustness',()=>{assert.equal(C.stress(E.blank()).available,false);assert.ok(C.adversary(E.blank()).findings.some(f=>f.rule==='sensitivity'));});
await test('Inactive approvals and costs are not current challenges',()=>{const p=E.demo();p.options.forEach(o=>o.decision='reject');p.options=p.options.filter(o=>o.type!=='requirement');assert.ok(!C.adversary(p).findings.some(f=>['authority','funding','evidence'].includes(f.rule)));});
await test('Year-only reminder is not an exact overdue deadline and ICS escapes text',()=>{const p=E.demo(),o=E.selected(p)[0];p.enablers.push({...E.enabler(),id:'annual-reminder',optionId:o.id,title:'Plan, review; next\nline',dueYear:2027});const m=C.milestones(p,'2027-08-01').find(x=>x.id==='annual-reminder');assert.equal(m.kind,'year');assert.equal(m.overdue,false);assert.ok(C.calendar(p).includes('Plan\\, review\\; next\\nline'));});
await test('Bounded compressed decode and payload size',async()=>{await assert.rejects(()=>S.encode({data:'x'.repeat(S.MAX+1)}));await assert.rejects(()=>S.decode('g.'+'A'.repeat(S.MAX*2)));});
await test('Saved AI strategy review stays current after council-only changes',async()=>{let p=E.demo();E.addContextReview(p,{model:'synthetic',summary:'Synthetic review',items:[]});assert.equal(E.contextReviewIsCurrent(p),true);p=await C.checkpoint(p,{label:'Review',nextDate:'2027-03-01'});assert.equal(E.contextReviewIsCurrent(p),true);p.institution.mission='Changed';assert.equal(E.contextReviewIsCurrent(p),false);});
await test('Board chart converts delta target to absolute value',()=>{const p=E.demo(),t=p.transitions.find(t=>E.selected(p).some(o=>o.id===t.optionId));t.direction='delta';t.baseline=10;t.target=5;t.unit='units';const text=SultanBoard.model(p).flatMap(s=>s.elements).filter(e=>e.type==='text').map(e=>e.text);assert.ok(text.includes('15 units'));});
console.log(JSON.stringify({suite:'council',tests:count,passed:count}));
})().catch(e=>{console.error(e);process.exitCode=1;});
