'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),E=require('../src/import.js');
const results=[];function test(name,f){try{f();results.push({name,pass:true});}catch(e){results.push({name,pass:false,error:e.message});console.error('FAIL',name,e.message);}}
const near=(a,b)=>assert(Math.abs(a-b)<1e-7,`${a} != ${b}`),issue=(p,word)=>E.check(p).some(x=>x.message.includes(word));
test('Blank project roundtrip',()=>{E.validateImport(E.blank());assert.equal(E.blank().options.length,0)});
test('Fictional example schema',()=>{const p=E.demo();assert(p.isDemo);E.validateImport(p)});
test('Four year horizon',()=>assert.deepEqual(E.years(E.demo()),[2027,2028,2029,2030]));
test('Invalid horizon',()=>{const p=E.demo();p.institution.endYear=2020;assert.throws(()=>E.validateImport(p))});
test('Maximum horizon',()=>{const p=E.demo();p.institution.endYear=2060;assert.throws(()=>E.validateImport(p))});
test('Weights must sum to 100',()=>{const p=E.demo();p.criteria[0].weight=20;assert.equal(E.score(p,p.options[0]).value,null)});
test('Negative weight',()=>{const p=E.demo();p.criteria[0].weight=-1;assert(!E.weightInfo(p).valid)});
test('Known weighted sum',()=>{const p=E.demo();near(E.score(p,p.options[0]).value,83)});
test('Zero is observed',()=>{const p=E.demo();Object.values(p.options[0].scores).forEach(s=>s.value=0);near(E.score(p,p.options[0]).value,0)});
test('Missing scores are bounds not zero',()=>{const p=E.demo();p.options[0].scores.identity.value=null;const s=E.score(p,p.options[0]);assert.equal(s.value,null);near(s.high-s.low,25)});
test('Partial excluded from ranking',()=>{const p=E.demo();delete p.options[0].scores.identity;assert(!E.ranking(p).some(r=>r.id==='o1'))});
test('Zero weight unknown allowed',()=>{const p=E.demo();p.criteria[0].weight=0;p.criteria[1].weight+=25;delete p.options[0].scores.identity;assert(E.score(p,p.options[0]).value!==null)});
test('Mandatory outside optional rank',()=>{const p=E.demo();p.options[0].type='requirement';assert(!E.ranking(p).some(r=>r.id==='o1'))});
test('Unselected obligation shown',()=>{const p=E.demo();p.options[0].type='requirement';p.options[0].decision='defer';assert(issue(p,'إلزاميًا'))});
test('Moonshot remains eligible without history',()=>{const p=E.demo();p.transitions[1].history=[];assert.equal(E.ranking(p)[0].id,'o2')});
test('History is not strategic value',()=>{const p=E.demo(),r=E.ranking(p);p.transitions[0].history[0].value=999;p.transitions[0].rf=.01;assert.deepEqual(E.ranking(p),r)});
test('RF respects year gaps',()=>near(E.historySummary({rf:.5,history:[{year:2024,value:10},{year:2026,value:20}]}).value,18));
test('Missing history remains missing',()=>near(E.historySummary({rf:.5,history:[{year:2024,value:null},{year:2026,value:.9}]}).value,.9));
test('No history',()=>assert.equal(E.historySummary({rf:.75,history:[]}).value,null));
test('Duplicate history year',()=>assert(E.historySummary({rf:.5,history:[{year:2026,value:1},{year:2026,value:2}]}).error));
test('RF zero rejected in this adaptation',()=>assert(E.historySummary({rf:0,history:[]}).error));
test('RF one mean',()=>near(E.historySummary({rf:1,history:[{year:2024,value:10},{year:2026,value:20}]}).value,15));
test('Up progress',()=>near(E.progress({baseline:10,direction:'up'},{actual:15,target:20}),50));
test('Down progress',()=>near(E.progress({baseline:20,direction:'down'},{actual:15,target:10}),50));
test('Qualitative has no numeric progress',()=>assert.equal(E.progress({baseline:1,direction:'qualitative'},{actual:2,target:3}),null));
test('Zero denominator has no progress',()=>assert.equal(E.progress({baseline:1,direction:'up'},{actual:1,target:1}),null));
test('Eight local weight scenarios',()=>assert.equal(E.sensitivity(E.demo()).trials.length,8));
test('Known budget gap',()=>{const b=E.budgetSummary(E.demo())[1];near(b.declared,550000);near(b.gap,50000)});
test('Deferred option excluded from budget',()=>{const p=E.demo();p.options[1].decision='defer';near(E.budgetSummary(p)[1].declared,300000)});
test('Unknown budget counted',()=>{const p=E.demo();p.initiatives[0].budget[0].amount=null;assert.equal(E.budgetSummary(p)[0].unknown,1)});
test('Unknown funding not zero assurance',()=>{const p=E.demo();p.funding[0].available=null;assert.equal(E.budgetSummary(p)[0].gap,null)});
test('Blocker does not change value',()=>{const p=E.demo(),r=E.ranking(p);p.enablers[0].status='blocked';assert(E.check(p).some(x=>x.entity==='i1'&&x.level==='blocking'));assert.deepEqual(E.ranking(p),r)});
test('Deleted link flagged',()=>{const p=E.demo();p.options.shift();assert(issue(p,'اختيار قائم'))});
test('Cross-choice link mismatch',()=>{const p=E.demo();p.initiatives[0].transitionId='t2';assert(issue(p,'مختلفين'))});
test('Unsuitable reference',()=>{const p=E.demo();p.references[0].status='notApplicable';assert(issue(p,'غير مناسبة'))});
test('Adaptation requires explanation',()=>{const p=E.demo();p.references[0].status='adapt';assert(issue(p,'التكييف'))});
test('Context missing remains visible',()=>{const p=E.demo();p.references[0].context='';assert(issue(p,'ملاءمة سياق'))});
test('Dependency cycle',()=>{const p=E.demo();p.initiatives[1].dependsOn=['i3'];assert(E.cycles(p).length)});
test('Initiative beyond horizon',()=>{const p=E.demo();p.initiatives[0].endYear=2040;assert(issue(p,'خارج الأفق'))});
test('Terminal target mismatch',()=>{const p=E.demo();p.transitions[0].annual[3].target=99;assert(issue(p,'السنة الأخيرة'))});
test('Extend horizon preserves observations',()=>{const p=E.demo();p.institution.endYear=2031;E.syncYears(p);assert.equal(p.transitions[0].annual.length,5);near(p.transitions[0].annual[0].target,2)});
test('Import clears review label',()=>{const p=E.demo();p.reviewedRevision=p.revision;assert.equal(E.validateImport(p).reviewedRevision,null)});
test('Prototype pollution rejected',()=>{const p=E.demo();p.extra=JSON.parse('{"__proto__":{"evil":1}}');assert.throws(()=>E.validateImport(p))});
test('Unsafe ID rejected',()=>{const p=E.demo();p.criteria[0].id='x\" onclick=evil';assert.throws(()=>E.validateImport(p))});
test('Duplicate IDs rejected',()=>{const p=E.demo();p.options[0].id=p.options[1].id;assert.throws(()=>E.validateImport(p))});
test('Malformed log rejected',()=>{const p=E.demo();p.log=[null];assert.throws(()=>E.validateImport(p))});
test('Duplicate annual budget rejected',()=>{const p=E.demo();p.initiatives[0].budget.push(p.initiatives[0].budget[0]);assert.throws(()=>E.validateImport(p))});
test('Negative budget rejected',()=>{const p=E.demo();p.initiatives[0].budget[0].amount=-1;assert.throws(()=>E.validateImport(p))});
test('Impossible score rejected',()=>{const p=E.demo();p.options[0].scores.identity.value=101;assert.throws(()=>E.validateImport(p))});
test('Full project roundtrip',()=>{const p=E.demo();assert.deepEqual(E.validateImport(JSON.parse(JSON.stringify(p))),p)});
test('Score before explanation can be saved',()=>{const p=E.demo();p.options[0].scores.identity={value:65};const q=E.validateImport(p);assert.equal(q.options[0].scores.identity.note,'');assert(issue(q,'فسّر'))});
test('Explanation before score stays unknown',()=>{const p=E.demo();p.options[0].scores.identity={note:'draft'};const q=E.validateImport(p);assert.equal(q.options[0].scores.identity.value,null)});
test('Invalid override weights rejected',()=>{const p=E.demo();assert.equal(E.score(p,p.options[0],{identity:100,benefit:100,distinct:100,sustain:100}).value,null)});
test('Fractional initiative year rejected',()=>{const p=E.demo();p.initiatives[0].startYear=2027.5;assert.throws(()=>E.validateImport(p))});
test('Invalid funding year rejected',()=>{const p=E.demo();p.funding[0].year=2090;assert.throws(()=>E.validateImport(p))});
test('Unselected strategy remains draft',()=>{const p=E.demo();p.options.forEach(o=>o.decision='consider');assert(issue(p,'لم يُحدد أي اختيار'))});
let seed=271;const random=()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/4294967296);
for(let i=0;i<100;i++)test('Property '+(i+1)+': bounds/order/monotonicity',()=>{const p=E.demo(),o=p.options[0];for(const c of p.criteria)o.scores[c.id].value=random()*100;const before=E.score(p,o).value;assert(before>=0&&before<=100);p.criteria.reverse();near(E.score(p,o).value,before);o.scores.identity.value=Math.min(100,o.scores.identity.value+5);assert(E.score(p,o).value>=before-1e-9)});
const summary={tests:results.length,passed:results.filter(x=>x.pass).length,failed:results.filter(x=>!x.pass).length,results};fs.mkdirSync(path.join(__dirname,'../qa'),{recursive:true});fs.writeFileSync(path.join(__dirname,'../qa/engine-results.json'),JSON.stringify(summary,null,2));console.log(JSON.stringify({...summary,results:undefined}));if(summary.failed)process.exitCode=1;
