'use strict';
const assert=require('node:assert/strict');
global.SultanLocales={en:require('../src/locales/en.js'),ar:require('../src/locales/ar.js')};
for(const f of ['final','guided','field-guide','lens','strategy'])require('../src/locales/'+f+'.js');
global.SultanI18n=require('../src/i18n.js');global.Sultan=require('../src/import.js');
for(const f of ['final-core','context-core','sector-library','draft-engine','expert-lens','strategy-core','goal-planner'])require('../src/'+f+'.js');
const E=Sultan,G=SultanGoalPlanner;let count=0;
async function test(name,fn){await fn();count++;console.log('PASS '+name);}
(async()=>{
await test('Goals alone generate linked metrics, benchmark plans and execution cards',async()=>{const base=E.blank(),snapshot=JSON.stringify(base);const {project:p,counts}=await G.generate(base,'Grow recurring revenue\nImprove service experience');assert.deepEqual(counts,{goals:2,kpis:2,initiatives:6});assert.equal(JSON.stringify(base),snapshot);assert.equal(p.strategy.charters.length,6);assert.equal(p.references.length,2);assert.equal(p.strategy.opportunities.length,2);assert.ok(p.initiatives.every(i=>p.options.some(o=>o.id===i.optionId)&&p.transitions.some(t=>t.id===i.transitionId)));assert.ok(p.strategy.charters.every(c=>c.activities.length===3&&c.costs.length===2&&c.risks.length===1));assert.ok(p.transitions.every(t=>t.baseline===null&&t.target===null&&t.annual.every(a=>a.target===null&&a.actual===null)));assert.ok(p.initiatives.every(i=>i.budgetStatus==='unconfirmed'&&i.budget.every(b=>b.amount===null)));assert.ok(p.references.every(r=>r.status==='unchecked'&&r.source===''));assert.ok(SultanStrategy.issues(p).length>0);assert.deepEqual(E.validateImport(p),p);});
await test('Repeat generation is idempotent and preserves edited records',async()=>{let {project:p}=await G.generate(E.blank(),'Improve service experience');p.transitions[0].baseline=0;p.transitions[0].target=80;p.initiatives[0].owner='Actual assigned owner';p.strategy.charters[0].sponsor='Actual sponsor';p.strategy.charters[0].costs[0].unitCost=0;const expected=E.clone(p);let {project:q}=await G.generate(p,'Improve service experience');for(const k of ['options','transitions','references','initiatives','strategy'])assert.deepEqual(q[k],expected[k]);});
await test('Goal parser deduplicates lines and refuses excessive inputs',()=>{assert.deepEqual(G.parse('1. Improve service\n- Improve service\n• Reduce cost'),['Improve service','Reduce cost']);assert.throws(()=>G.parse('x'.repeat(301)));assert.throws(()=>G.parse(Array.from({length:11},(_,i)=>'Goal '+i).join('\n')));});
await test('Existing goal completion preserves zero budgets and custom KPIs',async()=>{const p=E.blank(),o=SultanDraft.addCustomGoal(p,{title:'Improve results',kpi:'User defined outcome',baseline:0,target:50});const i=Object.assign(E.initiative(p),{optionId:o.id,transitionId:p.transitions[0].id,title:'Existing activity'});i.budget[0].amount=0;p.initiatives.push(i);const {project:q}=await G.generate(p,'');assert.equal(q.initiatives.length,1);assert.equal(q.transitions[0].kpi,'User defined outcome');assert.equal(q.initiatives[0].budget[0].amount,0);assert.equal(q.strategy.charters.length,1);});
await test('Deferred and rejected choices are not silently selected',async()=>{const p=E.blank(),o=SultanDraft.addCustomGoal(p,{title:'Deferred objective'});o.decision='defer';await assert.rejects(()=>G.generate(p,o.title));assert.equal(p.options[0].decision,'defer');});
await test('One-year activities are sequential and within the initiative horizon',async()=>{const base=E.blank();base.institution.endYear=base.institution.startYear;const {project:p}=await G.generate(base,'Reduce cost');assert.ok(!SultanStrategy.issues(p).some(x=>x.code==='dates'||x.code==='costYear'));for(const c of p.strategy.charters){assert.ok(c.activities[0].end<c.activities[1].start);assert.ok(c.activities[1].end<c.activities[2].start);}});
await test('Arabic and English goals infer distinct proposed measurement families',()=>{assert.equal(G.theme('تنمية الإيرادات المتكررة'),'growth');assert.equal(G.theme('تقليل زمن تقديم الخدمة'),'efficiency');assert.equal(G.theme('تحسين تجربة المستفيد'),'service');assert.equal(G.theme('تقليل المخاطر'),'risk');assert.equal(G.theme('Develop employee skills'),'people');assert.equal(G.theme('Novel institutional goal'),'outcome');});
await test('Unconfigured AI never receives data and falls back to local generation',async()=>{let called=false;global.SultanAI={configured:()=>false,generateStrategy:async()=>{called=true;}};const r=await G.generate(E.blank(),'Improve service',{useAI:true});assert.equal(called,false);assert.equal(r.mode,'local');});
await test('AI failure still returns a complete local draft',async()=>{global.SultanAI={configured:()=>true,generateStrategy:async()=>{throw Error('Offline');}};const r=await G.generate(E.blank(),'Improve service',{useAI:true});assert.equal(r.fallback,true);assert.equal(r.project.initiatives.length,3);});
await test('AI isolates new goals and cannot overwrite existing measured records',async()=>{let {project:p}=await G.generate(E.blank(),'Existing service');p.transitions[0].baseline=0;p.transitions[0].target=88;const original=E.clone(p);let seed;global.SultanAI={configured:()=>true,generateStrategy:async args=>{seed=args.project;return {data:{options:[{key:'n',sourceOptionId:seed.options[0].id,title:seed.options[0].title}],transitions:[{key:'t',optionKey:'n',kpi:'Retention rate',unit:'%',direction:'up',baseline:99,target:100}]},truncated:false};}};const r=await G.generate(p,'Grow recurring revenue\nReduce cost',{useAI:true});assert.equal(seed.options.length,2);assert.ok(!seed.options.some(o=>o.title==='Existing service'));assert.equal(r.mode,'ai');assert.deepEqual(r.project.transitions.find(t=>t.id===original.transitions[0].id),original.transitions[0]);assert.ok(r.project.options.some(o=>o.title==='Reduce cost'));assert.equal(r.project.transitions.find(t=>t.kpi==='Retention rate').baseline,null);assert.ok(r.project.initiatives.length>=9);});
await test('Enabled benchmark research flows into the draft as proposed evidence',async()=>{let memo='';global.SultanAI={configured:()=>true,settings:()=>({webSearch:true}),gatherContext:async()=>({memo:'Synthetic sourced comparison; unapproved',data:{sources:[{title:'Synthetic benchmark source',kind:'benchmark',issuer:'Fictional institute',url:'https://example.org/benchmark',year:2025,summary:'Synthetic observation',relevance:'Comparison'}]},truncated:false}),generateStrategy:async args=>{memo=args.benchmarkMemo;return {data:{options:[]},truncated:false};}};const r=await G.generate(E.blank(),'Improve service',{useAI:true});assert.equal(r.mode,'ai');assert.ok(memo.includes('Synthetic'));assert.ok(r.project.context.sources.some(s=>s.title==='Synthetic benchmark source'&&s.status==='proposed'));assert.equal(r.project.transitions[0].baseline,null);});
await test('Research failure is explicit and does not stop the execution draft',async()=>{global.SultanAI={configured:()=>true,settings:()=>({webSearch:true}),gatherContext:async()=>{throw Error('Unavailable');},generateStrategy:async()=>({data:{options:[]},truncated:false})};const r=await G.generate(E.blank(),'Improve service',{useAI:true});assert.equal(r.researchPending,true);assert.equal(r.project.initiatives.length,3);});
await test('All goal strings have Arabic and English equivalents',()=>{for(const key of Object.keys(SultanLocales.en).filter(k=>k.startsWith('gp')))assert.equal(typeof SultanLocales.ar[key],'string',key);});
console.log(JSON.stringify({suite:'goal-planner',tests:count,passed:count}));
})().catch(e=>{console.error(e);process.exitCode=1;});
