'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8');
const js=read('src/methodology-layer.js'),css=read('src/methodology-layer.css'),locale=read('src/locales/methodology.js'),rev3=read('src/rev3-handoff.js'),index=read('index.html'),build=read('build.py');
for(const token of ['smC1','smC2','smC3','smC4','smC5'])assert.ok(locale.includes(token),token);
for(const phrase of ['Auditable Choice','Authority Space','Decision Break-even','Unknown ≠ Zero','Evidence-Gated Funding','الاختيار القابل للفحص','مساحة الصلاحية','نقطة تعادل القرار','المجهول ≠ صفر','التمويل المشروط بالدليل'])assert.ok(locale.includes(phrase),phrase);
assert.equal((locale.match(/\bsmR[1-5]\s*:/g)||[]).length,0,'methodology locale must not redefine canonical R1-R5');
for(const phrase of ["smR1:'R1 · Unapproved borrowed target'","smR2:'R2 · Boundary contradiction'","smR3:'R3 · Trade-off omission'","smR4:'R4 · Choice distinctiveness'","smR5:'R5 · Advantage grounding'","smR1:'R1 · مستهدف مستعار غير معتمد'","smR2:'R2 · تناقض الحدود'","smR3:'R3 · غياب المفاضلة'","smR4:'R4 · تمايز الخيارات'","smR5:'R5 · تأصيل الميزة'"])assert.ok(rev3.includes(phrase),phrase);
assert.ok(js.includes('<svg')&&!js.includes('<canvas')&&!js.includes('<foreignObject'));
assert.ok(!/\b(fetch|XMLHttpRequest|sendBeacon)\s*\(/.test(js),'methodology layer must not transmit data');
for(const asset of ['src/home-value.css','src/methodology-layer.css','src/palette-unify.css','src/audit-fixes.css','src/rev3-handoff.css','src/locales/home-value.js','src/locales/methodology.js','src/home-value.js','src/methodology-layer.js','src/audit-fixes.js','src/rev3-handoff.js'])assert.ok(index.includes(asset),'index must declare '+asset);
assert.ok(!build.includes("html.replace(\n    '</body>'")&&!build.includes("html.replace(\n    '</head>'"),'build must not inject runtime layers');
for(const forbidden of ['#1c6658','#0f3038','#15383d','#173c44','#60736e','#7d9d8a','#42646a'])assert.ok(!css.includes(forbidden),'legacy green/teal in methodology CSS: '+forbidden);
const ctx={globalThis:{SultanLocales:{en:{},ar:{}}}};vm.createContext(ctx);vm.runInContext(locale,ctx);const en=ctx.globalThis.SultanLocales.en,ar=ctx.globalThis.SultanLocales.ar;
for(const k of Object.keys(en)){assert.equal(typeof ar[k],'string','Arabic counterpart: '+k);assert.ok(en[k].trim()&&ar[k].trim(),k);}assert.ok(Object.keys(en).length>=30);
console.log(JSON.stringify({suite:'methodology-layer',passed:true,keys:Object.keys(en).length,rules:5,constructs:5,network:false,canonicalRules:'rev3-handoff'}));
