"""Studio acceptance: complete user journeys on synthetic data, in Arabic and English."""
from pathlib import Path
import functools, http.server, json, os, threading
from playwright.sync_api import sync_playwright, expect
BASE=Path(__file__).resolve().parents[1]; QA=BASE/'qa'; QA.mkdir(exist_ok=True)
LIVE=os.environ.get('SULTAN_LIVE_URL','');server=None
if LIVE:url=LIVE
else:
 server=http.server.ThreadingHTTPServer(('127.0.0.1',0),functools.partial(http.server.SimpleHTTPRequestHandler,directory=str(BASE/'public')))
 threading.Thread(target=server.serve_forever,daemon=True).start();url=f'http://127.0.0.1:{server.server_port}/'
results=[]
def check(name,ok):
 results.append({'name':name,'pass':bool(ok)})
 if not ok:raise AssertionError(name)
try:
 with sync_playwright() as pw:
  opts={'headless':True}
  if os.environ.get('CHROMIUM_PATH'):opts['executable_path']=os.environ['CHROMIUM_PATH']
  browser=pw.chromium.launch(**opts)
  for lang in ['ar','en']:
   ctx=browser.new_context(viewport={'width':1366,'height':900},accept_downloads=True)
   page=ctx.new_page();errors=[];page.on('pageerror',lambda e:errors.append(str(e)))
   page.goto(url+'?lang='+lang,wait_until='load')
   page.evaluate('''()=>{const p=Sultan.blank();p.institution.name='Synthetic studio QA';const o=Sultan.option();Object.assign(o,{title:'Synthetic recurring service',decision:'select',whyUs:'Synthetic delivery capability'});p.options.push(o);const t=Sultan.transition(p);Object.assign(t,{optionId:o.id,kpi:'Synthetic service score',baseline:40,target:65});p.transitions.push(t);const i=Sultan.initiative(p);Object.assign(i,{title:'Synthetic pilot',optionId:o.id,transitionId:t.id,owner:'Test lead'});p.initiatives.push(i);SultanApp.setProject(p);SultanApp.navigate('strategy');}''')
   page.locator('[data-sw="enable"]').click();expect(page.locator('#sw-panel')).to_be_visible()
   page.locator('[data-path="strategy.assessment.problem"]').fill('Synthetic decision problem')
   page.locator('[data-path="strategy.assessment.evidence"]').fill('Synthetic interviews')
   page.locator('[data-sw-tab="services"]').click()
   expect(page.locator('.svc-catalog')).to_be_visible()
   check(lang+' service catalog exposes thirteen services',page.locator('.svc-card').count()==13)
   page.locator('[data-sw="svc-add-shift"]').click()
   page.locator('[data-path="strategy.services.shifts.0.shiftType"]').select_option('channel')
   page.locator('[data-path="strategy.services.shifts.0.signal"]').fill('Synthetic AI-mediated distribution shift')
   page.locator('[data-path="strategy.services.shifts.0.evidence"]').fill('Synthetic channel evidence')
   page.locator('[data-path="strategy.services.shifts.0.implication"]').fill('Synthetic interface ownership risk');page.locator('[data-path="strategy.services.shifts.0.implication"]').press('Tab')
   expect(page.locator('[data-svc-key="shift"] .svc-status')).to_have_class(/done/)
   check(lang+' shift and channel services require evidence',page.evaluate('SultanStrategy.serviceReadiness(SultanApp.getProject()).shift.done && SultanStrategy.serviceReadiness(SultanApp.getProject()).channel.done'))
   page.locator('[data-sw="svc-add-inaction"]').click()
   page.locator('[data-path="strategy.services.inaction.0.decision"]').fill('Experiment now or wait')
   page.locator('[data-path="strategy.services.inaction.0.consequence"]').fill('Lose a learning window')
   page.locator('[data-path="strategy.services.inaction.0.window"]').fill('90 days')
   page.locator('[data-path="strategy.services.inaction.0.inactionCost"]').fill('Delayed evidence and partner access')
   page.locator('[data-path="strategy.services.inaction.0.owner"]').fill('Strategy lead')
   page.locator('[data-path="strategy.services.inaction.0.reviewDate"]').fill('2027-03-31');page.locator('[data-path="strategy.services.inaction.0.reviewDate"]').press('Tab')
   expect(page.locator('[data-svc-key="inaction"] .svc-status')).to_have_class(/done/)
   check(lang+' cost-of-inaction service completes without invented action cost',page.evaluate('SultanStrategy.serviceReadiness(SultanApp.getProject()).inaction.done && SultanApp.getProject().strategy.services.inaction[0].actionCost===""'))
   page.locator('[data-path="strategy.services.watch.owner"]').fill('Strategy office')
   page.locator('[data-path="strategy.services.watch.triggers"]').fill('Channel share changes; new regulation')
   page.locator('[data-path="strategy.services.watch.nextReviewDate"]').fill('2027-06-30');page.locator('[data-path="strategy.services.watch.nextReviewDate"]').press('Tab')
   expect(page.locator('[data-svc-key="watch"] .svc-status')).to_have_class(/done/)
   check(lang+' watch plan is explicit and scheduled',page.evaluate('SultanStrategy.serviceReadiness(SultanApp.getProject()).watch.done'))
   check(lang+' service report contains evidence',page.evaluate('SultanStrategy.report(SultanApp.getProject()).includes("Synthetic AI-mediated distribution shift") && SultanStrategy.report(SultanApp.getProject()).includes("Delayed evidence and partner access")'))
   page.reload(wait_until='load')
   expect(page.locator('[data-path="strategy.services.shifts.0.signal"]')).to_have_value('Synthetic AI-mediated distribution shift')
   check(lang+' service records survive reload',page.evaluate('SultanApp.getProject().strategy.services.inaction.length===1 && SultanApp.getProject().strategy.services.watch.owner==="Strategy office"'))
   page.locator('[data-sw-tab="opportunities"]').click()
   page.locator('[data-sw="add-opportunity"]').click()
   page.locator('[data-path="strategy.opportunities.0.segment"]').fill('Synthetic segment')
   page.locator('[data-path="strategy.opportunities.0.buyer"]').fill('Synthetic buyer')
   page.locator('[data-path="strategy.opportunities.0.annualContract"]').fill('120000')
   page.locator('[data-path="strategy.opportunities.0.customers"]').fill('6')
   page.locator('[data-path="strategy.opportunities.0.recurringShare"]').fill('75')
   page.locator('[data-path="strategy.opportunities.0.grossMargin"]').fill('35')
   check(lang+' economic calculation',page.evaluate('SultanStrategy.economics(SultanApp.getProject().strategy.opportunities[0]).recurring===540000'))
   page.locator('[data-path="strategy.opportunities.0.grossMargin"]').press('Tab')
   check(lang+' visible economic values',page.locator('[data-sw-economics="0"] strong').count()==3)
   page.reload(wait_until='load');expect(page.locator('[data-path="strategy.opportunities.0.buyer"]')).to_have_value('Synthetic buyer')
   check(lang+' reload preserves studio and field values',page.evaluate('SultanApp.getProject().strategy.opportunities[0].annualContract===120000'))
   page.locator('[data-sw-tab="delivery"]').click()
   page.locator('[data-path="strategy.opportunities.0.route"]').select_option('partner')
   expect(page.locator('[data-path="strategy.opportunities.0.partnerIncentive"]')).to_be_visible()
   page.locator('[data-path="strategy.opportunities.0.ourContribution"]').fill('Synthetic delivery network')
   page.locator('[data-path="strategy.opportunities.0.partnerIncentive"]').fill('Synthetic buyer access')
   page.locator('[data-path="strategy.opportunities.0.partnerEvidence"]').fill('Synthetic meeting record')
   page.locator('[data-sw-tab="operating"]').click()
   page.locator('[data-path="strategy.operating.mode"]').select_option('reuse')
   expect(page.locator('[data-path="strategy.operating.targetModel"]')).to_have_count(0)
   page.locator('[data-path="strategy.operating.currentModel"]').fill('Synthetic approved model')
   page.locator('[data-sw-tab="execution"]').click();page.locator('[data-sw="add-charter"]').click()
   page.locator('[data-path="strategy.charters.0.sponsor"]').fill('Synthetic sponsor')
   page.locator('[data-path="strategy.charters.0.scope"]').fill('Synthetic pilot scope')
   page.locator('.sw-details').filter(has=page.locator('[data-sw="add-row"][data-kind="cost"]')).locator('summary').click()
   page.locator('[data-sw="add-row"][data-kind="cost"]').click()
   page.locator('[data-path="strategy.charters.0.costs.0.label"]').fill('Synthetic support')
   page.locator('[data-path="strategy.charters.0.costs.0.unit"]').fill('month')
   page.locator('[data-path="strategy.charters.0.costs.0.quantity"]').fill('3')
   page.locator('[data-path="strategy.charters.0.costs.0.unitCost"]').fill('10000')
   page.once('dialog',lambda d:d.accept());page.locator('[data-sw="sync-budget"]').click()
   check(lang+' explicit budget transfer without approval',page.evaluate('SultanApp.getProject().initiatives[0].budget[0].amount===30000 && SultanApp.getProject().initiatives[0].budgetStatus==="unconfirmed"'))
   page.locator('[data-sw-tab="review"]').click();expect(page.locator('.sw-stage-grid')).to_be_visible()
   check(lang+' open issues visible',page.locator('.sw-issues li').count()>0)
   check(lang+' report includes studio content',page.evaluate('SultanApp.getReport().includes("Synthetic buyer") && SultanApp.getReport().includes("Synthetic sponsor") && SultanApp.getReport().includes("Synthetic support")'))
   check(lang+' import roundtrip',page.evaluate('JSON.stringify(Sultan.validateImport(SultanApp.getProject()))===JSON.stringify(SultanApp.getProject())'))
   for stage in ['services','opportunities','delivery','operating','execution','review']:
    page.locator('[data-sw-tab="'+stage+'"]').click();page.set_viewport_size({'width':390,'height':844})
    check(lang+' mobile '+stage,page.evaluate('document.documentElement.scrollWidth<=innerWidth+1'))
    page.set_viewport_size({'width':1366,'height':900})
   page.locator('[data-sw-tab="opportunities"]').click()
   page.screenshot(path=str(QA/f'strategy-studio-{lang}.png'),full_page=True)
   page.evaluate("()=>{SultanApp.setProject(Sultan.blank());SultanApp.navigate('strategy');}")
   goals='تنمية الإيرادات المتكررة\nتحسين تجربة المستفيد' if lang=='ar' else 'Grow recurring revenue\nImprove service experience'
   page.locator('#gp-goals').fill(goals)
   page.locator('[data-gp="generate"]').click()
   expect(page.locator('[data-sw-tab="execution"]')).to_have_attribute('aria-selected','true')
   check(lang+' goals generate all linked plans',page.evaluate('SultanApp.getProject().options.length===2 && SultanApp.getProject().transitions.length===2 && SultanApp.getProject().initiatives.length===6 && SultanApp.getProject().strategy.charters.length===6'))
   check(lang+' generated benchmarks remain unchecked',page.evaluate('SultanApp.getProject().references.length===2 && SultanApp.getProject().references.every(r=>r.status==="unchecked" && !r.source)'))
   check(lang+' generated budgets remain unknown',page.evaluate('SultanApp.getProject().initiatives.every(i=>i.budgetStatus==="unconfirmed" && i.budget.every(b=>b.amount===null))'))
   page.locator('[data-gp="existing"]').click()
   expect(page.locator('[data-gp="existing"]')).to_be_enabled()
   check(lang+' repeated completion does not duplicate',page.evaluate('SultanApp.getProject().initiatives.length===6 && SultanApp.getProject().strategy.charters.length===6'))
   page.reload(wait_until='load')
   check(lang+' generated strategy survives reload',page.evaluate('SultanApp.getProject().strategy.charters.length===6'))
   page.set_viewport_size({'width':390,'height':844})
   check(lang+' mobile goal generation',page.evaluate('document.documentElement.scrollWidth<=innerWidth+1'))
   page.screenshot(path=str(QA/f'goal-planner-{lang}.png'),full_page=True)
   page.set_viewport_size({'width':1366,'height':900})
   page.evaluate('''()=>{SultanAI.configured=()=>true;SultanAI.generateStrategy=()=>new Promise(resolve=>window.resolveTestDraft=resolve);SultanApp.navigate('strategy');}''')
   page.locator('#gp-goals').fill('Synthetic new objective during editing')
   page.locator('[data-gp="generate"]').click()
   expect(page.locator('[data-gp="generate"]')).to_be_disabled()
   page.evaluate('''()=>{const p=SultanApp.getProject();p.institution.name='Concurrent user edit';SultanApp.setProject(p);window.resolveTestDraft({data:{options:[]},truncated:false});}''')
   expect(page.locator('#gp-status')).to_contain_text('تغير المشروع' if lang=='ar' else 'project changed')
   check(lang+' concurrent edit survives AI result',page.evaluate('SultanApp.getProject().institution.name==="Concurrent user edit" && SultanApp.getProject().options.length===2'))
   check(lang+' no script errors',not errors)
   ctx.close()
  browser.close()
finally:
 if server:server.shutdown()
report={'tests':len(results),'passed':sum(r['pass'] for r in results),'results':results,'live':bool(LIVE),'url':url}
(QA/'strategy-browser-results.json').write_text(json.dumps(report,indent=2,ensure_ascii=False))
print(f'Strategy studio browser checks: {report["passed"]}/{report["tests"]}')
