/* On-demand local exports. One layout model drives editable PPTX and fixed PDF. */
(function(root){
'use strict';
const T=(k,v)=>root.SultanI18n.t(k,v),E=root.Sultan,C=root.SultanCouncil;
const W=1600,H=900,NAVY='0B2D63',GOLD='CAA85E',IVORY='F7F3EA',INK='263A54';
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=x=>E.num(x)?x.toLocaleString('en-US',{maximumFractionDigits:2}):T('coUnknown');
const libraries={zip:'jszip-3.10.2.js',pptx:'pptxgen-4.0.1.js',pdf:'jspdf-4.2.1.js'};let loading;
function load(){return loading||(loading=(async()=>{for(const [key,file] of Object.entries(libraries)){if(key==='zip'&&root.JSZip||key==='pptx'&&root.PptxGenJS||key==='pdf'&&root.jspdf)continue;await new Promise((resolve,reject)=>{const s=document.createElement('script'),embedded=document.getElementById('sultan-library-'+key);if(embedded){s.textContent=embedded.textContent;document.head.append(s);resolve();}else{s.src=root.SULTAN_ASSETS?.['vendor/'+file]||'src/vendor/'+file;s.onload=resolve;s.onerror=()=>reject(Error(T('coOfflineUnavailable')));document.head.append(s);}});}})().catch(e=>{loading=null;throw e;}));}
const ar=()=>root.SultanI18n.language==='ar';
function model(p,basis=''){const slides=[],selected=E.selected(p),ids=new Set(selected.map(o=>o.id)),funding=E.budgetSummary(p),due=C.milestones(p),last=p.council.reviews.at(-1),changes=C.diff(p,p.council.checkpoints.at(-1));
 function page(title,note=''){const s={title,elements:[]};s.elements.push({type:'rect',x:0,y:0,w:W,h:H,fill:'FFFFFF'},{type:'rect',x:0,y:0,w:W,h:140,fill:NAVY},{type:'rect',x:70,y:164,w:90,h:6,fill:GOLD});text(s,title,70,38,1460,72,40,'FFFFFF',true);text(s,`SULTAN ${root.SULTAN_VERSION} · ${T('coRevision')} ${p.revision} · ${slides.length+1}`,70,842,1100,28,17,INK);if(note)text(s,note,70,780,1460,45,18,INK);slides.push(s);return s;}
 function text(s,value,x,y,w,h,size=25,color=INK,bold=false){s.elements.push({type:'text',text:String(value??T('coUnknown')),x,y,w,h,size,color,bold});}
 function bar(s,x,y,w,h,value,max,color){s.elements.push({type:'rect',x,y,w,h,fill:'E8EBEF'});if(E.num(value)&&value>=0&&max>0)s.elements.push({type:'rect',x,y,w:Math.max(1,w*value/max),h,fill:color});}
 function cards(title,records,render,count=3){if(!records.length){const s=page(title);text(s,T('coBoardNoData'),80,270,1440,180,32);return;}for(let start=0;start<records.length;start+=count){const s=page(title,T('coBoardDetails'));records.slice(start,start+count).forEach((r,i)=>render(s,r,205+i*(540/count),540/count-20));}}
 let s=page(T('coBoardCover'));text(s,p.institution.name||'SULTAN',80,230,1440,150,64,NAVY,true);text(s,p.institution.vision||p.institution.mission||T('coBoardDisclaimer'),80,410,1440,140,30,INK);const stats=[[T('coSelected'),selected.length],[T('coOpenAuthority'),p.enablers.filter(e=>ids.has(e.optionId)&&e.status!=='ready').length],[T('coUnknownCosts'),funding.reduce((n,b)=>n+b.unknown,0)],[T(due[0]?.kind==='year'?'coYearOnly':'coNextReview'),due[0]?(due[0].kind==='year'?due[0].date.slice(0,4):due[0].date):T('coUnknown')]];stats.forEach(([label,value],i)=>{const x=80+i*370;s.elements.push({type:'rect',x,y:610,w:345,h:130,fill:IVORY});text(s,value,x+20,630,305,50,34,NAVY,true);text(s,label,x+20,686,305,40,21,INK);});
 cards(T('coBoardDecisions'),selected,(s,o,y,h)=>{text(s,o.title,80,y,520,h,29,NAVY,true);text(s,[o.decisionReason||o.outcome,o.tradeoff?T('s304')+': '+o.tradeoff:T('coNoTradeoff'),T('coOwner')+': '+(o.owner||T('coUnknown'))].join('\n'),650,y,870,h,23);},3);
 const max=Math.max(1,...funding.flatMap(b=>[b.declared,b.available]).filter(E.num));for(let start=0;start<funding.length;start+=5){s=page(T('coBoardFunding'),T('coNoCurrency'));funding.slice(start,start+5).forEach((b,i)=>{const y=205+i*110;text(s,String(b.year),80,y,130,50,28,NAVY,true);bar(s,270,y+10,670,22,b.declared,max,NAVY);bar(s,270,y+48,670,22,b.available,max,GOLD);text(s,`${T('coRequested')}: ${fmt(b.declared)}\n${T('coAvailable')}: ${fmt(b.available)}`,980,y,530,68,21);text(s,`${T('coGap')}: ${fmt(b.gap)} · ${T('coUnknownCosts')}: ${b.unknown}`,270,y+76,1100,32,18);});}
 const auth=E.authoritySpace?E.authoritySpace(p).filter(r=>ids.has(r.id)||r.decision==='select'||r.type==='requirement'):[];
 cards(T('coBoardAuthority'),auth,(s,r,y,h)=>{text(s,r.title,80,y,560,h,28,NAVY,true);const clearance=r.clearance;bar(s,690,y+10,780,36,clearance,100,NAVY);text(s,`${T('authorityClearance')}: ${fmt(clearance)}${E.num(clearance)?'%':''}`,690,y+65,780,54,24);},4);
 const trs=p.transitions.filter(t=>ids.has(t.optionId));cards(T('coBoardProgress'),trs,(s,t,y,h)=>{text(s,t.kpi||t.domain,80,y,480,h,26,NAVY,true);const actual=t.annual.filter(a=>E.num(a.actual)).at(-1)?.actual,values=[t.baseline,E.absoluteTarget?E.absoluteTarget(t,{target:t.target}):t.target,actual],max=Math.max(1,...values.filter(E.num).map(Math.abs));values.forEach((v,j)=>{const yy=y+j*43;bar(s,730,yy+5,540,20,E.num(v)&&v>=0?v:null,max,[NAVY,GOLD,'62798F'][j]);text(s,T(['coBaseline','coTarget','coActual'][j]),530,yy,190,37,18);text(s,fmt(v)+' '+(t.unit||''),1290,yy,240,37,18);});},3);
 const initiatives=E.selectedInitiatives(p),years=E.years(p);cards(T('coBoardTimeline'),initiatives,(s,i,y,h)=>{text(s,i.title,80,y,630,h,25,NAVY,true);const x=770,width=690,unit=width/Math.max(1,years.length);s.elements.push({type:'rect',x,y:y+38,w:width,h:20,fill:'E8EBEF'},{type:'rect',x:x+(i.startYear-years[0])*unit,y:y+38,w:Math.max(unit,(i.endYear-i.startYear+1)*unit),h:20,fill:GOLD});text(s,`${i.startYear} – ${i.endYear} · ${i.owner||T('coUnknown')}`,x,y,width,34,20);},5);
 const review=last||C.adversary(p);cards(T('coBoardReview'),review.findings,(s,f,y,h)=>{text(s,f.subject||T('coChallenge'),80,y,420,h,26,NAVY,true);text(s,`${f.challenge}\n${T('coTest')}: ${f.test}`,550,y,970,h,23);},3);
 cards(T('coBoardPositions'),p.council.responses,(s,r,y,h)=>{text(s,r.owner,80,y,420,h,27,NAVY,true);text(s,`${T(r.basis===basis?'coCurrent':'coStale')}\n${T({support:'coSupport',changes:'coChanges',abstain:'coAbstain'}[r.stance])}\n${r.comment}`,550,y,970,h,23);},3);
 s=page(T('coBoardNext'),T('coReminderLimits'));text(s,T('coWhatChanged')+': '+changes.length,80,210,1440,65,33,NAVY,true);text(s,changes.slice(0,5).map(r=>r.label).join('\n')||T(p.council.checkpoints.length?'coNoChanges':'coNoCheckpoint'),80,295,700,400,23);text(s,due.slice(0,6).map(m=>`${m.kind==='year'?m.date.slice(0,4):m.date}  ${m.title}${m.kind==='year'?' ('+T('coYearOnly')+')':''}`).join('\n')||T('coNone'),830,295,690,400,23);return slides;
}
function wrap(ctx,text,width){const lines=[];for(const paragraph of String(text).split('\n')){let line='';for(const word of paragraph.split(/\s+/)){if(ctx.measureText(word).width>width){if(line){lines.push(line);line='';}let part='';for(const char of word){if(ctx.measureText(part+char).width>width){lines.push(part);part='';}part+=char;}line=part;continue;}if(line&&ctx.measureText(line+' '+word).width>width){lines.push(line);line=word;}else line+=(line?' ':'')+word;}lines.push(line);}return lines;}
function layoutText(ctx,e){let size=e.size,lines=[];do{ctx.font=`${e.bold?'bold ':''}${size}px Arial, sans-serif`;lines=wrap(ctx,e.text,e.w);if(lines.length*size*1.3<=e.h)break;size--;}while(size>Math.max(17,e.size-6));const max=Math.max(1,Math.floor(e.h/(size*1.3)));if(lines.length>max){lines=lines.slice(0,max);lines[max-1]=lines[max-1].replace(/.{1,6}$/u,'')+'…';}return {size,lines};}
function renderCanvas(slide){const canvas=document.createElement('canvas');canvas.width=W;canvas.height=H;const ctx=canvas.getContext('2d');for(const e of slide.elements){if(e.type==='rect'){ctx.fillStyle='#'+e.fill;ctx.fillRect(e.x,e.y,e.w,e.h);}else{const {size,lines}=layoutText(ctx,e);ctx.font=`${e.bold?'bold ':''}${size}px Arial, sans-serif`;ctx.direction=ar()?'rtl':'ltr';ctx.textAlign=ar()?'right':'left';ctx.textBaseline='top';ctx.fillStyle='#'+e.color;lines.forEach((line,i)=>ctx.fillText(line,ar()?e.x+e.w:e.x,e.y+i*size*1.3));}}return canvas;}
function appendix(p,report,basis){const r=p.council.reviews.at(-1)||C.adversary(p);return `<!doctype html><html lang="${root.SultanI18n.language}" dir="${ar()?'rtl':'ltr'}"><meta charset="utf-8"><title>SULTAN Board appendix</title><style>body{font:16px/1.8 Arial,sans-serif;max-width:1100px;margin:auto;padding:32px;color:#0b2d63}table{border-collapse:collapse;width:100%}td,th{padding:9px;border:1px solid #bbb;text-align:start;white-space:pre-wrap}h1,h2,h3{break-after:avoid}section{margin:24px 0}dt{font-weight:bold}dd{margin:0 0 12px}svg{max-width:100%}.hint{background:#f7f3ea;padding:12px}</style><h1>${esc(T('coFullAppendix'))}</h1><p>${esc(T('coBoardDisclaimer'))}</p>${report}<h2>${esc(T('coBoardReview'))}</h2>${p.council.reviews.length?'<p>'+esc(T(r.basis===basis?'coCurrent':'coStale'))+'</p>':''}${root.SultanCouncilUI.findingsHtml(r)}<h2>${esc(T('coBoardPositions'))}</h2><p>${esc(T('coOwnerPosition'))}</p>${p.council.responses.map(x=>`<h3>${esc(x.owner)}</h3><p>${esc(T({support:'coSupport',changes:'coChanges',abstain:'coAbstain'}[x.stance]))}</p><p>${esc(x.comment)}</p><p>${esc(x.at)} · ${esc(T(x.basis===basis?'coCurrent':'coStale'))}</p>`).join('')}<h2>${esc(T('coWhatChanged'))}</h2>${root.SultanCouncilUI.differences(p)}<h2>${esc(T('coMilestones'))}</h2>${C.milestones(p).map(x=>`<p>${esc(x.kind==='year'?x.date.slice(0,4)+' ('+T('coYearOnly')+')':x.date)} · ${esc(x.title)} · ${esc(x.owner)}</p>`).join('')}<h2>${esc(T('coHistory'))}</h2>${p.council.checkpoints.map(x=>`<p>${esc(x.at)} · ${esc(x.label)} · ${esc(x.note)} · ${esc(x.nextDate)}</p>`).join('')}</html>`;}
async function exportPack(p){const original=E.clone(p),report=root.SultanApp.getReport();await load();await document.fonts.ready;for(const r of p.council.responses)if(!await C.verifyResponse(p,r))throw Error(T('coUnverified'));const current=await C.basis(p),r=p.council.reviews.at(-1);if(r&&r.basis!==current){p=E.clone(p);p.council.reviews=[];}const slides=model(p,current),pres=new root.PptxGenJS();pres.layout='LAYOUT_WIDE';pres.author='SULTAN';pres.subject=T('coBoardDisclaimer');pres.title=p.institution.name||'SULTAN';pres.company='SULTAN';pres.lang=ar()?'ar-SA':'en-US';pres.theme={headFontFace:'Arial',bodyFontFace:'Arial',lang:pres.lang};const pdf=new root.jspdf.jsPDF({orientation:'landscape',unit:'pt',format:[960,540],compress:true});const zip=new root.JSZip(),measure=document.createElement('canvas').getContext('2d');
 for(let i=0;i<slides.length;i++){const s=slides[i],page=pres.addSlide();for(const e of s.elements){if(e.type==='rect')page.addShape(pres.ShapeType.rect,{x:e.x/120,y:e.y/120,w:e.w/120,h:e.h/120,line:{color:e.fill,transparency:100},fill:{color:e.fill}});else{const {size,lines}=layoutText(measure,e);page.addText(lines.join('\n'),{x:e.x/120,y:e.y/120,w:e.w/120,h:e.h/120,fontFace:'Arial',fontSize:size*.6,color:e.color,bold:e.bold,margin:0,breakLine:false,rtlMode:ar(),align:ar()?'right':'left',valign:'top',paraSpaceAfterPt:0,lineSpacingMultiple:1.15});}}page.addNotes(T('coBoardDetails'));if(i)pdf.addPage([960,540],'landscape');pdf.addImage(renderCanvas(s).toDataURL('image/jpeg',.94),'JPEG',0,0,960,540,undefined,'FAST');}
 zip.file('SULTAN_Board.pptx',await pres.write({outputType:'arraybuffer',compression:true}));zip.file('SULTAN_Board.pdf',pdf.output('arraybuffer'));zip.file('SULTAN_Board_Appendix.html',appendix(original,report,current));zip.file('SULTAN_Review_Dates.ics',C.calendar(p));const blob=await zip.generateAsync({type:'blob',compression:'DEFLATE'});root.SultanCouncilUI.download('SULTAN_Board_Pack.zip',blob,'application/zip');return {slides:slides.length,bytes:blob.size};}
root.SultanBoard={model,renderCanvas,exportPack,load};
})(globalThis);
