(function(root){
'use strict';
const E=root.Sultan,C=root.SultanCouncil,S=root.SultanShare,T=(k,v)=>root.SultanI18n.t(k,v),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let tab='share',busy=false,links=[],linksBasis='';
const button=(label,action,primary=false)=>`<button type="button" class="btn ${primary?'primary':''}" data-co="${action}">${esc(T(label))}</button>`;
const field=(key,id,type='text',help='',extra='')=>`<label class="field"><span>${esc(T(key))}</span>${type==='textarea'?`<textarea id="${id}" rows="3" ${extra}></textarea>`:`<input id="${id}" type="${type}" ${extra}>`}${help?`<span class="help">${esc(T(help))}</span>`:''}</label>`;
function status(message){const el=document.getElementById('co-status');if(el)el.textContent=message;}
function download(name,data,type){const blob=data instanceof Blob?data:new Blob([data],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
function refresh(){root.SultanApp.navigate('council');}
function policy(){const s=root.SultanAI.settings();return `<details class="co-policy"><summary>${esc(T('coPrivacy'))}</summary><p>${esc(T(s.transport==='proxy'?'coRelayPolicy':'coDirectPolicy'))}</p><p><b>${esc(T('coProvider'))}:</b> <bdi>${esc(s.model)}</bdi></p><p><b>${esc(T('coEndpoint'))}:</b> <bdi>${esc(s.transport==='proxy'?s.endpoint:'https://api.anthropic.com')}</bdi></p><p>${esc(T('coAIData'))}</p>${s.model.startsWith('gemini-')?`<p>${esc(T('coGoogleData'))}</p>`:''}<p><a href="https://ai.google.dev/gemini-api/terms" target="_blank" rel="noopener noreferrer">${esc(T('coPolicyGoogle'))}</a> · <a href="https://www.anthropic.com/legal/commercial-terms" target="_blank" rel="noopener noreferrer">${esc(T('coPolicyAnthropic'))}</a></p><button type="button" class="btn" data-gw-action="ai-settings">${esc(T('aiSettings'))}</button></details>`;}
function linksHtml(){return links.map((x,i)=>`<article class="co-link"><h3>${esc(x.owner||T('coReadTitle'))}</h3>${x.url?`<textarea readonly aria-label="${esc(T('coCopy'))}" dir="ltr">${esc(x.url)}</textarea><button class="btn" type="button" data-co-copy="${i}">${esc(T('coCopy'))}</button>`:`<p>${esc(T('coLargeLink'))}</p>`}<button class="btn" type="button" data-co-file="${i}">${esc(T('coSignedFile'))}</button></article>`).join('');}
function share(p){if(linksBasis!==S.canonical(C.snapshot(p)))links=[];return `<p>${esc(T('coShareLead'))}</p><details open class="co-policy"><summary>${esc(T('coShareScope'))}</summary><p>${esc(T('coShareLimits'))}</p></details><label class="co-consent"><input id="co-share-consent" type="checkbox"> ${esc(T('coShareConsent'))}</label><div class="co-owners">${[1,2,3].map(i=>field('coOwner','co-owner-'+i,'text','',`maxlength="100" aria-label="${esc(T('coOwner'))} ${i}"`)).join('')}${field('coDays','co-days','number','', 'value="14" min="1" max="90"')}</div><div class="toolbar">${button('coReadLink','read',true)}${button('coInvites','invite')}</div><div id="co-links">${linksHtml()}</div><hr>${field('coReply','co-reply','textarea','coReplyHelp','maxlength="480000"')}<div class="toolbar">${button('coImportReply','accept',true)}${button('coChooseReply','reply-file')}</div><p class="hint">${esc(T('coOwnerPosition'))}</p><div class="co-responses">${p.council.requests.length?p.council.requests.map(r=>{const response=p.council.responses.find(x=>x.requestId===r.id);return `<article class="co-response" data-request="${esc(r.id)}"><h3>${esc(r.owner)}</h3><p>${esc(response?T({support:'coSupport',changes:'coChanges',abstain:'coAbstain'}[response.stance]):T('coAwaiting'))}</p>${response?`<p>${esc(response.comment)}</p><time>${esc(response.at)}</time><p class="co-validity" role="status"></p>`:''}</article>`;}).join(''):`<p>${esc(T('coNoResponses'))}</p>`}</div>`;}
function findingsHtml(r){return `<p class="co-review-summary">${esc(r.summary)}</p>${r.findings.map(f=>`<article class="co-finding"><h3>${esc(f.subject||T('coChallenge'))}</h3><dl><dt>${esc(T('coEvidence'))}</dt><dd>${esc(f.evidence)}</dd><dt>${esc(T('coChallenge'))}</dt><dd>${esc(f.challenge)}</dd><dt>${esc(T('coTest'))}</dt><dd>${esc(f.test)}</dd></dl></article>`).join('')}`;}
function adversary(p){const r=p.council.reviews.at(-1),s=C.stress(p);return `<p>${esc(T('coAdversaryLead'))}</p><p class="hint">${esc(T('coReviewAdvisory'))}</p>${policy()}<div class="toolbar">${button('coRunLocal','local',true)}</div><label class="co-consent"><input id="co-ai-consent" type="checkbox"> ${esc(T('coAIConsent'))}</label>${button('coRunAI','ai')}<section class="co-stress"><h2>${esc(T('coStressResult'))}</h2><p>${esc(T('coStressNote'))}</p>${s.available?`<div class="co-table"><table><thead><tr><th>${esc(T('coField'))}</th><th>${esc(T('coBefore'))}</th><th>${esc(T('coAfter'))}</th><th>${esc(T('coChallenge'))}</th></tr></thead><tbody>${s.trials.map(t=>`<tr><td>${esc(t.criterion)}</td><td>${t.from.toFixed(2)}%</td><td>${t.to.toFixed(2)}%</td><td>${esc(T(t.changed?'coLeaderChanged':'coLeaderStable'))}: ${esc(t.top.join(' / '))}</td></tr>`).join('')}</tbody></table></div>`:`<p>${esc(T('coStressMissing'))}</p>`}</section>${r?`<section class="co-review"><span class="pill">${esc(T(r.source==='local'?'coLocalMode':'coAIMode'))}</span> <bdi>${esc(r.model)}</bdi><p class="co-review-validity"></p>${findingsHtml(r)}</section>`:''}`;}
function format(x){if(x===null||x===undefined||x==='')return T('coUnknown');return typeof x==='object'?JSON.stringify(x):String(x);}
function differences(p){const cp=p.council.checkpoints.at(-1);if(!cp)return `<p>${esc(T('coNoCheckpoint'))}</p>`;const rows=C.diff(p,cp);return rows.length?`<div class="co-table"><table><thead><tr><th>${esc(T('coField'))}</th><th>${esc(T('coBefore'))}</th><th>${esc(T('coAfter'))}</th></tr></thead><tbody>${rows.map(r=>`<tr><th>${esc(r.label)}</th><td>${esc(format(r.before))}</td><td>${esc(format(r.after))}</td></tr>`).join('')}</tbody></table></div>`:`<p>${esc(T('coNoChanges'))}</p>`;}
function journal(p){const due=C.milestones(p);return `<p>${esc(T('coJournalLead'))}</p><h2>${esc(T('coWhatChanged'))}</h2>${differences(p)}<details class="co-checkpoint-form" open><summary>${esc(T('coSaveCheckpoint'))}</summary><div class="grid2">${field('coCheckpointLabel','co-label','text','coCheckpointHelp','maxlength="160"')}${field('coCheckpointDate','co-date','date')}</div>${field('coCheckpointNote','co-note','textarea','','maxlength="4000"')}${button('coSaveCheckpoint','checkpoint',true)}<p class="help">${esc(T('coKeep12'))}</p></details><h2>${esc(T('coMilestones'))}</h2><p>${esc(T('coReminderLimits'))}</p><div class="toolbar">${button('coDownloadCalendar','calendar')}${button('coJumpAssumptions','assumptions')}</div>${due.length?due.map(m=>`<article class="co-milestone"><time>${esc(m.kind==='year'?m.date.slice(0,4):m.date)}</time><b>${esc(m.title)}</b><span>${esc(m.owner)}</span>${m.kind==='year'?`<small>${esc(T('coYearOnly'))}</small>`:''}${m.overdue?`<span class="pill warn">${esc(T('coOverdue'))}</span>`:''}</article>`).join(''):`<p>${esc(T('coNone'))}</p>`}<details><summary>${esc(T('coHistory'))} (${p.council.checkpoints.length})</summary>${p.council.checkpoints.slice().reverse().map(c=>`<article><h3>${esc(c.label)}</h3><p>${esc(c.note)}</p><p>${esc(c.at)} · ${esc(T('coNextReview'))}: ${esc(c.nextDate)}</p></article>`).join('')}</details>`;}
function board(){return `<p>${esc(T('coBoardLead'))}</p><p class="co-desktop-note">${esc(T('coDesktop'))}</p><ol class="co-pack-outline">${['coBoardCover','coBoardDecisions','coBoardFunding','coBoardAuthority','coBoardProgress','coBoardTimeline','coBoardReview','coBoardPositions','coBoardNext'].map(k=>`<li>${esc(T(k))}</li>`).join('')}</ol>${button('coBoardAction','board',true)}<p class="help">${esc(T('coBoardNote'))}</p>`;}
function view(){const p=root.SultanApp?.getProject()||E.blank();return `<div class="heading"><h1 tabindex="-1">${esc(T('coTitle'))}</h1><p>${esc(T('coLead'))}</p></div><div class="co-tabs" role="tablist">${[['share','coShare'],['board','coBoard'],['adversary','coAdversary'],['journal','coJournal']].map(([k,label])=>`<button type="button" role="tab" id="co-tab-${k}" aria-controls="co-panel" aria-selected="${tab===k}" data-co-tab="${k}">${esc(T(label))}</button>`).join('')}</div><div class="card co-panel" id="co-panel" role="tabpanel" aria-labelledby="co-tab-${tab}">${({share,board,adversary,journal}[tab])(p)}</div><p id="co-status" role="status" aria-live="polite"></p>`;}
async function renderStates(){if(location.hash!=='#council')return;const p=root.SultanApp.getProject(),b=await C.basis(p);for(const r of p.council.responses){const el=document.querySelector(`[data-request="${r.requestId}"] .co-validity`);if(el)el.textContent=await C.verifyResponse(p,r)?T(r.basis===b?'coCurrent':'coStale'):T('coUnverified');}const el=document.querySelector('.co-review-validity');if(el)el.textContent=T(p.council.reviews.at(-1)?.basis===b?'coCurrent':'coStale');}
document.addEventListener('sultan:render',()=>{setTimeout(()=>{const menu=document.querySelector('.export-menu-panel');if(menu&&!menu.querySelector('[data-co="board-shortcut"]'))menu.insertAdjacentHTML('afterbegin',button('coBoardAction','board-shortcut',true));const saved=document.querySelector('.fm-saved');if(saved&&!document.querySelector('.co-home-reminder')){const next=C.milestones(root.SultanApp.getProject())[0];if(next)saved.insertAdjacentHTML('afterend',`<button class="co-home-reminder btn ghost" type="button" data-co="journal-shortcut">${esc(T(next.kind==='year'?'coYearOnly':'coNextReview'))}: ${esc(next.kind==='year'?next.date.slice(0,4):next.date)}</button>`);}const side=document.querySelector('.sidefoot');if(side&&!side.querySelector('[data-co="offline"]'))side.insertAdjacentHTML('beforeend',button('coOffline','offline'));renderStates();},0);});
document.addEventListener('click',async e=>{const t=e.target.closest('[data-co-tab]');if(t){tab=t.dataset.coTab;refresh();document.getElementById('co-tab-'+tab)?.focus();return;}const linkButton=e.target.closest('[data-co-copy],[data-co-file]');if(linkButton){const x=links[Number(linkButton.dataset.coCopy??linkButton.dataset.coFile)];if(linkButton.hasAttribute('data-co-copy')){try{await navigator.clipboard.writeText(x.url);status(T('coCopied'));}catch{linkButton.parentElement.querySelector('textarea')?.select();}}else download('SULTAN_signed_snapshot.json',JSON.stringify(x.packet),'application/json');return;}
 const b=e.target.closest('[data-co]');if(!b||busy)return;const action=b.dataset.co;if(action==='board-shortcut'||action==='journal-shortcut'){tab=action==='board-shortcut'?'board':'journal';refresh();return;}if(action==='assumptions'){root.SultanApp.navigate('choices');return;}if(action==='reply-file'){const input=document.createElement('input');input.type='file';input.accept='.json';input.onchange=async()=>{try{const f=input.files[0];if(f.size>S.MAX*2)throw Error(T('coLimit'));const packet=JSON.parse(await f.text());document.getElementById('co-reply').value=await S.encode(packet);}catch(err){status(T('coError')+err.message);}};input.click();return;}
 busy=true;b.disabled=true;status(T('coWorking'));
 try{const p=root.SultanApp.getProject(),before=await C.basis(p);let next,message='';
 if(action==='read'||action==='invite'){if(!document.getElementById('co-share-consent').checked)throw Error(T('coConsentRequired'));const owners=action==='invite'?[1,2,3].map(i=>document.getElementById('co-owner-'+i).value.trim()):[],r=await C.createLinks(p,owners,Number(document.getElementById('co-days').value));links=[];linksBasis=S.canonical(C.snapshot(p));for(const packet of r.packets){const token=await S.encode(packet);links.push({packet,owner:packet.payload.owner,url:token.length<=S.LINK_MAX?S.link(token):''});}next=r.project;message=T('coLinksReady');}
 else if(action==='accept'){next=await C.accept(p,document.getElementById('co-reply').value);message=T('coRecorded');}
 else if(action==='checkpoint'){next=await C.checkpoint(p,{label:document.getElementById('co-label').value.trim(),nextDate:document.getElementById('co-date').value,note:document.getElementById('co-note').value.trim()});message=T('coCheckpointSaved');}
 else if(action==='calendar'){download('SULTAN_review_dates.ics',C.calendar(p),'text/calendar;charset=utf-8');message=T('coReminderLimits');}
 else if(action==='local'||action==='ai'){let r,model='local-rules';status(T('coReviewBusy'));if(action==='ai'){if(!document.getElementById('co-ai-consent').checked||!root.SultanAI.configured())throw Error(T('coAIRequired'));r=await root.SultanAI.adversarialReview({project:p});model=r.usage.model||root.SultanAI.settings().model;p.context.ai.log.push({at:new Date().toISOString(),model,purpose:'adversarial-review',inputTokens:r.usage.inputTokens,outputTokens:r.usage.outputTokens});r=r.data;}else r=C.adversary(p);p.council.reviews.push({id:E.uid('red'),at:new Date().toISOString(),basis:before,source:action==='ai'?'ai':'local',model,summary:r.summary,findings:r.findings});p.council.reviews=p.council.reviews.slice(-12);next=E.validateImport(p);}
 else if(action==='board'){status(T('coBoardBusy'));await root.SultanBoard.exportPack(p);message=T('coBoardDone');}
 else if(action==='offline'){await root.SultanOffline.prepare();message=T('coOfflineReady');}
 if(next){if(await C.basis(root.SultanApp.getProject())!==before)throw Error(T('coReviewChanged'));root.SultanApp.setProject(next);}
 status(message);
 }catch(err){console.error(err);status(T('coError')+err.message);}finally{busy=false;if(b.isConnected)b.disabled=false;}
});
root.SultanCouncilUI={view,findingsHtml,differences,policy,download,open:(which='share')=>{tab=which;refresh();}};
if(location.hash==='#council')refresh();
})(globalThis);
