/* SULTAN Strategy Builder 0.5.1 — local, deterministic decision support.
   Preference scores are not approval or probabilities of success. */
(function(root){
'use strict';
const SCHEMA='sultan.strategy.v0.5';
const clone=x=>JSON.parse(JSON.stringify(x));
const num=x=>typeof x==='number'&&Number.isFinite(x);
const text=x=>typeof x==='string'&&x.trim().length>0;
const uid=p=>(p||'id')+'_'+(typeof crypto!=='undefined'&&crypto.randomUUID?crypto.randomUUID().slice(0,8):Math.random().toString(36).slice(2,10));
function years(p){const a=p.institution.startYear,b=p.institution.endYear;return Number.isInteger(a)&&Number.isInteger(b)&&b>=a&&b-a<=15?Array.from({length:b-a+1},(_,i)=>a+i):[];}
function criteria(){return [
 {id:'identity',name:'ملاءمة هوية الجهة',weight:25,low:'لا يقدّم سببًا خاصًا بهذه الجهة',high:'مساهمة محددة تستثمر أصلًا مميزًا للجهة'},
 {id:'benefit',name:'الأثر على المستفيد',weight:35,low:'لا تحسن محددًا في نتيجة تخص المستفيد',high:'تحسن كبير موصوف بدليل أو فرضية قابلة للاختبار'},
 {id:'distinct',name:'التميز الاستراتيجي',weight:25,low:'تكرار لما تقدمه الجهات الأخرى دون مبرر',high:'دور متميز يحتاجه المستفيد وتملك الجهة سببًا لقيادته'},
 {id:'sustain',name:'استمرار القيمة',weight:15,low:'منفعة عابرة أو تنقل الضرر إلى الآخرين',high:'منفعة مستمرة مع معالجة الأثر على المنظومة الأوسع'}
];}
function blank(){return {schema:SCHEMA,isDemo:false,revision:0,reviewedRevision:null,reviewNote:'',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),institution:{name:'',sector:'',mission:'',beneficiaries:'',assets:'',context:'',culture:'',vision:'',notDoing:'',startYear:2027,endYear:2030},mandates:[],criteria:criteria(),weightRationale:'',options:[],references:[],transitions:[],enablers:[],initiatives:[],funding:[],log:[]};}
function option(){return {id:uid('opt'),title:'',type:'differentiation',outcome:'',whyUs:'',foothold:'',tradeoff:'',owner:'',decision:'consider',decisionReason:'',scores:{}};}
function reference(){return {id:uid('ref'),name:'',kind:'benchmark',source:'',purpose:'',context:'',adaptation:'',status:'unchecked'};}
function transition(p){return {id:uid('tr'),optionId:'',referenceId:'',domain:'',current:'',currentSource:'',targetState:'',kpi:'',unit:'',direction:'up',baseline:null,target:null,owner:'',dataSource:'',frequency:'ربع سنوي',rf:0.75,history:[],annual:years(p).map(year=>({year,milestone:'',target:null,evidence:'',actual:null,actualSource:'',observation:''}))};}
function enabler(){return {id:uid('en'),optionId:'',title:'',kind:'capability',action:'add',control:'unknown',owner:'',status:'unknown',dueYear:null,source:'',route:'',fallback:''};}
function initiative(p){return {id:uid('in'),optionId:'',transitionId:'',title:'',kind:'build',owner:'',startYear:p.institution.startYear,endYear:p.institution.startYear,output:'',acceptance:'',capacity:'',budgetStatus:'unconfirmed',status:'design',dependsOn:[],enablerIds:[],budget:years(p).map(year=>({year,amount:null}))};}
function weightInfo(p){const vals=p.criteria.map(c=>c.weight);const sum=vals.reduce((a,b)=>a+(num(b)?b:0),0);return {sum,valid:vals.length>0&&vals.every(v=>num(v)&&v>=0&&v<=100)&&Math.abs(sum-100)<1e-6};}
function score(p,o,weights){const wi=weightInfo(p);if(!wi.valid&&!weights)return {value:null,low:null,high:null,coverage:0,reason:'weights'};if(weights){const ws=p.criteria.map(c=>weights[c.id]);if(!ws.every(w=>num(w)&&w>=0&&w<=100)||Math.abs(ws.reduce((a,b)=>a+b,0)-100)>1e-6)return {value:null,low:null,high:null,coverage:0,reason:'weights'};}let low=0,missing=0,coverage=0;for(const c of p.criteria){const w=weights?weights[c.id]:c.weight;const x=o.scores[c.id]?.value;if(num(x)&&x>=0&&x<=100){low+=w*x/100;coverage+=w;}else missing+=w;}return {value:missing>1e-8?null:low,low,high:low+missing,coverage,reason:missing?'incomplete':''};}
function ranking(p,weights){return p.options.filter(o=>o.type!=='requirement').map(o=>({id:o.id,title:o.title,...score(p,o,weights)})).filter(o=>o.value!==null).sort((a,b)=>b.value-a.value||a.id.localeCompare(b.id));}
function sensitivity(p){if(!weightInfo(p).valid)return {base:[],trials:[],switches:0};const base=ranking(p);if(base.length<2)return {base,trials:[],switches:0};const top=r=>r.length?r.filter(x=>Math.abs(x.value-r[0].value)<1e-7).map(x=>x.id).sort().join(','):'';let trials=[];for(const c of p.criteria){for(const delta of [-5,5]){const nw=c.weight+delta,remaining=100-c.weight;if(nw<0||nw>100||remaining<=0)continue;const w={};for(const k of p.criteria)w[k.id]=k.id===c.id?nw:k.weight*(100-nw)/remaining;const r=ranking(p,w);if(!r.length)continue;trials.push({criterion:c.name,delta,top:r.filter(x=>Math.abs(x.value-r[0].value)<1e-7).map(x=>x.title),changed:top(r)!==top(base)});}}return {base,trials,switches:trials.filter(t=>t.changed).length};}
function historySummary(t){if(!num(t.rf)||t.rf<=0||t.rf>1)return {value:null,error:'عامل التذكر يجب أن يكون أكبر من صفر وحتى 1.'};const all=t.history||[];const valid=all.filter(h=>Number.isInteger(h.year)&&num(h.value));if(!valid.length)return {value:null,count:0,missing:all.length,latest:null};if(new Set(valid.map(h=>h.year)).size!==valid.length)return {value:null,error:'توجد سنة تاريخية مكررة.'};const latest=Math.max(...valid.map(h=>h.year));let w=0,v=0;for(const h of valid){const a=Math.pow(t.rf,latest-h.year);w+=a;v+=a*h.value;}return {value:v/w,count:valid.length,missing:all.length-valid.length,latest,unreferenced:valid.filter(h=>!text(h.source)).length};}
function progress(t,row){if(!num(t.baseline)||!num(row?.actual)||!num(row?.target)||t.direction==='qualitative')return null;const d=row.target-t.baseline;if(d===0)return null;return 100*(row.actual-t.baseline)/d;}
function selected(p){return p.options.filter(o=>o.decision==='select');}
function selectedInitiatives(p){const ids=new Set(selected(p).map(o=>o.id));return p.initiatives.filter(i=>ids.has(i.optionId));}
function budgetSummary(p){const ins=selectedInitiatives(p);return years(p).map(year=>{let declared=0,unknown=0;for(const i of ins){if(year<i.startYear||year>i.endYear)continue;const b=i.budget.find(b=>b.year===year);if(num(b?.amount))declared+=b.amount;else unknown++;}const cap=p.funding.find(f=>f.year===year)?.available;return {year,declared,unknown,available:num(cap)?cap:null,gap:num(cap)?Math.max(0,declared-cap):null};});}
function cycles(p){const ids=new Set(p.initiatives.map(i=>i.id));const map=Object.fromEntries(p.initiatives.map(i=>[i.id,i.dependsOn.filter(x=>ids.has(x))]));const on=new Set(),done=new Set(),out=[];function visit(x,path){if(on.has(x)){out.push([...path,x]);return;}if(done.has(x))return;on.add(x);for(const d of map[x]||[])visit(d,[...path,x]);on.delete(x);done.add(x);}for(const id of ids)visit(id,[]);return out;}
function check(p){
 const out=[];const add=(section,level,message,entity='')=>out.push({section,level,message,entity});const I=p.institution;
 for(const [k,label] of [['name','اسم الجهة'],['mission','رسالة الجهة'],['beneficiaries','المستفيدون'],['assets','المقومات المميزة'],['context','السياق المؤسسي'],['culture','السلوك والحوافز ذات الصلة'],['vision','المستقبل المختار']])if(!text(I[k]))add('identity','missing','أكمل '+label+'.');
 if(!years(p).length)add('identity','blocking','الأفق يجب أن يكون بين سنة واحدة و16 سنة، بسنوات صحيحة.');
 for(const m of p.mandates)if(!text(m.source)||m.relationship==='unknown')add('identity','missing','تحقق من مصدر التكليف ودور الجهة: '+(m.title||'تكليف بلا عنوان'),m.id);
 if(!p.options.length)add('choices','missing','أضف بدائل استراتيجية قبل تصميم المبادرات.');
 for(const o of p.options){if(!text(o.title)||!text(o.outcome)||!text(o.whyUs)||!text(o.tradeoff))add('choices','missing','أكمل النتيجة وسبب الاختيار والمفاضلة: '+(o.title||'اختيار جديد'),o.id);if(o.type==='moonshot'&&!text(o.foothold))add('choices','missing','وثّق موطئ القدم والفرضية القابلة للاختبار للمونشوت؛ لا يشترط اكتمال القدرة: '+(o.title||''),o.id);if(o.decision!=='consider'&&!text(o.decisionReason))add('choices','missing','سجّل سبب قرارك بشأن '+(o.title||'الاختيار'),o.id);if(o.type==='requirement'&&o.decision!=='select')add('choices','warning','متطلب مصنف إلزاميًا ليس ضمن المسار المختار؛ راجع نطاق الإلزام ومبرر القرار: '+(o.title||''),o.id);}
 if(!weightInfo(p).valid)add('priorities','blocking','مجموع الأوزان يجب أن يساوي 100، دون قيم سالبة أو فارغة.');
 if(!selected(p).length)add('choices','missing','لم يُحدد أي اختيار ضمن المسار؛ هذه مسودة بدائل وليست استراتيجية مختارة.');
 for(const c of p.criteria)if(!text(c.name)||!text(c.low)||!text(c.high))add('priorities','missing','عرّف اسم المعيار وحدّي تقييمه: '+(c.name||'معيار جديد'),c.id);
 if(!text(p.weightRationale))add('priorities','missing','وثّق مبرر الأوزان؛ القيم الأولية أمثلة وليست معيارًا معتمدًا.');
 for(const o of p.options.filter(o=>o.type!=='requirement')){if(score(p,o).reason==='incomplete')add('priorities','missing','المفاضلة غير مكتملة: '+(o.title||'اختيار جديد'),o.id);for(const c of p.criteria){const s=o.scores[c.id];if(num(s?.value)&&c.weight>0&&!text(s.note))add('priorities','missing','فسّر تقييم «'+c.name+'» للبديل «'+(o.title||'')+'».',o.id);}}
 for(const r of p.references){if(r.status==='unchecked')add('references','missing','افحص ملاءمة المرجعية: '+(r.name||'مرجعية جديدة'),r.id);if(['use','adapt'].includes(r.status)&&!text(r.context))add('references','missing','وثّق ملاءمة سياق الجهة قبل استخدام المرجعية: '+(r.name||''),r.id);if(!text(r.source)||!text(r.purpose))add('references','missing','حدد مصدر المرجعية وغرضها: '+(r.name||''),r.id);if(r.status==='adapt'&&!text(r.adaptation))add('references','missing','اشرح التكييف وحدود النقل: '+r.name,r.id);}
 const optIds=new Set(p.options.map(o=>o.id));const trIds=new Set(p.transitions.map(t=>t.id));const inMap=Object.fromEntries(p.initiatives.map(i=>[i.id,i]));const enMap=Object.fromEntries(p.enablers.map(e=>[e.id,e]));
 for(const t of p.transitions){
  if(!optIds.has(t.optionId))add('references','blocking','اربط الانتقال باختيار قائم: '+(t.domain||'انتقال جديد'),t.id);
  if(!text(t.current)||!text(t.currentSource)||!text(t.targetState))add('references','missing','أكمل الوضع الحالي ومصدره والحالة المستهدفة: '+(t.domain||''),t.id);
  const r=p.references.find(r=>r.id===t.referenceId);if(!r)add('references','missing','حدد مرجعية الانتقال (قد تكون معيار تقييم داخليًا): '+(t.domain||''),t.id);else if(r.status==='notApplicable')add('references','blocking','الانتقال يستند إلى مرجعية مصنفة غير مناسبة: '+(t.domain||''),t.id);
  if(!text(t.kpi)||!text(t.dataSource)||!text(t.owner))add('references','missing','حدد المؤشر ومصدره ومالكه: '+(t.domain||''),t.id);
  if(t.direction!=='qualitative'&&(!num(t.baseline)||!num(t.target)))add('references','missing','خط الأساس والهدف الرقمي غير مكتملين: '+t.domain,t.id);
  if(num(t.baseline)&&num(t.target)&&((t.direction==='up'&&t.target<t.baseline)||(t.direction==='down'&&t.target>t.baseline)))add('references','blocking','اتجاه التحسن لا يتسق مع خط الأساس والهدف: '+t.domain,t.id);
  if(t.annual.some(a=>!text(a.milestone)||!text(a.evidence)||(t.direction!=='qualitative'&&!num(a.target))))add('references','missing','أكمل محطات السنوات وأدلة قبولها: '+t.domain,t.id);
  const last=t.annual.find(a=>a.year===I.endYear);if(t.direction!=='qualitative'&&num(last?.target)&&num(t.target)&&Math.abs(last.target-t.target)>1e-8)add('references','warning','هدف السنة الأخيرة يختلف عن الهدف النهائي: '+t.domain,t.id);
  if(t.annual.some(a=>num(a.actual)&&!text(a.actualSource)))add('review','missing','توجد قراءة فعلية بلا مصدر: '+t.domain,t.id);
  const h=historySummary(t);if(h.error)add('references','blocking',h.error+' '+t.domain,t.id);
 }
 for(const o of selected(p))if(!p.transitions.some(t=>t.optionId===o.id))add('references','missing','الاختيار المحدد بلا مسار من الوضع الحالي إلى المستهدف: '+o.title,o.id);
 for(const e of p.enablers){if(!optIds.has(e.optionId))add('enablers','blocking','اربط الممكن باختيار قائم: '+(e.title||''),e.id);if(!text(e.owner)||!text(e.source)||!text(e.route))add('enablers','missing','أكمل المالك والسند وطريقة التفعيل: '+(e.title||''),e.id);if(e.control!=='internal'&&!text(e.fallback))add('enablers','missing','حدد أثر تأخر أو عدم موافقة الجهة الخارجية: '+e.title,e.id);}
 for(const i of p.initiatives){
  if(!optIds.has(i.optionId))add('roadmap','blocking','مبادرة بلا اختيار استراتيجي قائم: '+(i.title||''),i.id);
  if(!trIds.has(i.transitionId))add('roadmap','missing','اربط المبادرة بانتقال محدد: '+(i.title||''),i.id);else if(p.transitions.find(t=>t.id===i.transitionId).optionId!==i.optionId)add('roadmap','blocking','المبادرة والانتقال مرتبطان باختيارين مختلفين: '+i.title,i.id);
  if(i.endYear<i.startYear||i.startYear<I.startYear||i.endYear>I.endYear)add('roadmap','blocking','توقيت المبادرة خارج الأفق أو نهايتها قبل بدايتها: '+i.title,i.id);
  if(!text(i.owner)||!text(i.output)||!text(i.acceptance)||!text(i.capacity))add('roadmap','missing','أكمل مسؤول المبادرة ومخرجها وقبولها ومواردها: '+i.title,i.id);
  if(i.budgetStatus!=='confirmed')add('roadmap','warning','التمويل غير مؤكد؛ إدراج المبادرة لا يعني تمويلها: '+i.title,i.id);
  for(const d of i.dependsOn){if(!inMap[d])add('roadmap','blocking','اعتمادية تشير لمبادرة محذوفة: '+i.title,i.id);else if(inMap[d].endYear>=i.startYear)add('roadmap','warning','راجع تسلسل «'+i.title+'» بعد «'+inMap[d].title+'»؛ التخطيط سنوي ولا يثبت ترتيبًا داخل السنة.',i.id);}
  for(const id of i.enablerIds){const e=enMap[id];if(!e)add('roadmap','blocking','ممكن مرتبط لم يعد موجودًا: '+i.title,i.id);else{if(e.status!=='ready')add('roadmap',e.status==='blocked'?'blocking':'warning','إطلاق «'+i.title+'» مشروط بمعالجة «'+e.title+'».',i.id);if(num(e.dueYear)&&e.dueYear>i.startYear)add('roadmap','warning','تاريخ الممكن بعد بدء المبادرة: '+i.title,i.id);}}
  if(i.budget.some(b=>(b.year<i.startYear||b.year>i.endYear)&&num(b.amount)&&b.amount>0))add('roadmap','warning','مبلغ خارج سنوات تنفيذ المبادرة غير محسوب ضمن إجمالي السنوات: '+i.title,i.id);
 }
 if(cycles(p).length)add('roadmap','blocking','توجد دورة اعتمادية بين المبادرات؛ راجع ترتيب العمل.');
 for(const b of budgetSummary(p)){if(b.unknown)add('roadmap','missing','ميزانية '+b.year+' غير مكتملة في '+b.unknown+' مبادرة مختارة.');if(b.gap>0)add('roadmap','warning','المبالغ المدخلة تتجاوز التمويل المتاح في '+b.year+' بمقدار '+b.gap.toLocaleString('en-US')+'.');}
 return out;
}
function syncYears(p){const ys=years(p);if(!ys.length)return;for(const t of p.transitions)t.annual=ys.map(year=>t.annual.find(a=>a.year===year)||{year,milestone:'',target:null,evidence:'',actual:null,actualSource:'',observation:''});for(const i of p.initiatives)i.budget=ys.map(year=>i.budget.find(b=>b.year===year)||{year,amount:null});p.funding=ys.map(year=>p.funding.find(f=>f.year===year)||{year,available:null});}
function validateImport(raw){
 if(!raw||typeof raw!=='object'||Array.isArray(raw))throw Error('الملف ليس مشروع سلطان.');
 let nodes=0;function scan(v,depth){if(++nodes>160000||depth>12)throw Error('الملف أكبر أو أعمق من حدود هذه النسخة.');if(typeof v==='string'&&v.length>24000)throw Error('حقل نصي طويل جدًا.');if(v&&typeof v==='object')for(const k of Object.keys(v)){if(['__proto__','prototype','constructor'].includes(k))throw Error('مفتاح غير مسموح في الملف.');scan(v[k],depth+1);}}scan(raw,0);
 if(raw.schema!==SCHEMA)throw Error('صيغة المشروع غير مدعومة. استخدم ملف تصدير مساحة سلطان 0.5.');
 const p=clone(raw),b=blank();if(typeof p.isDemo!=='boolean')throw Error('نوع المشروع غير محدد.');
 if(!p.institution||typeof p.institution!=='object')throw Error('بيانات الجهة مفقودة.');for(const k of Object.keys(b.institution))if(typeof p.institution[k]!==typeof b.institution[k])throw Error('حقل غير صالح في بيانات الجهة: '+k);if(!years(p).length)throw Error('أفق التخطيط غير صالح.');
 for(const k of ['criteria','options','references','transitions','enablers','initiatives','mandates','funding','log'])if(!Array.isArray(p[k])||p[k].length>(k==='log'?1000:250))throw Error('قائمة غير صالحة أو كبيرة: '+k);
 const ids=new Set();for(const k of ['criteria','options','references','transitions','enablers','initiatives','mandates'])for(const obj of p[k]){if(!obj||!text(obj.id)||!/^[A-Za-z0-9_-]{1,80}$/.test(obj.id)||ids.has(obj.id))throw Error('معرف مفقود أو مكرر.');ids.add(obj.id);}
 const field=(x,k,type,allowNull=false)=>{if(!x||typeof x!=='object')throw Error('سجل غير صالح.');if(allowNull&&x[k]===null)return;if(type==='number'?!num(x[k]):typeof x[k]!==type)throw Error('حقل غير صالح: '+k);};
 for(const c of p.criteria){for(const k of ['name','low','high'])field(c,k,'string');field(c,'weight','number',true);if(num(c.weight)&&(c.weight<0||c.weight>100))throw Error('وزن خارج النطاق.');}
 for(const o of p.options){for(const k of ['title','type','outcome','whyUs','foothold','tradeoff','owner','decision','decisionReason'])field(o,k,'string');if(!['requirement','differentiation','moonshot'].includes(o.type)||!['consider','select','defer','reject'].includes(o.decision))throw Error('تصنيف اختيار غير صالح.');if(!o.scores||typeof o.scores!=='object'||Array.isArray(o.scores))throw Error('تقييمات غير صالحة.');for(const s of Object.values(o.scores)){field(s,'value','number',true);field(s,'note','string');if(num(s.value)&&(s.value<0||s.value>100))throw Error('درجة خارج 0–100.');}}
 for(const r of p.references){for(const k of ['name','kind','source','purpose','context','adaptation','status'])field(r,k,'string');if(!['framework','benchmark','accreditation','internal'].includes(r.kind))throw Error('نوع مرجعية غير صالح.');if(!['unchecked','use','adapt','notApplicable'].includes(r.status))throw Error('حالة مرجعية غير صالحة.');}
 for(const t of p.transitions){for(const k of ['optionId','referenceId','domain','current','currentSource','targetState','kpi','unit','direction','owner','dataSource','frequency'])field(t,k,'string');for(const k of ['baseline','target'])field(t,k,'number',true);field(t,'rf','number');if(t.rf<=0||t.rf>1)throw Error('عامل تذكر غير صالح.');if(!['up','down','qualitative'].includes(t.direction))throw Error('اتجاه مؤشر غير صالح.');if(!Array.isArray(t.annual)||t.annual.length>16||!Array.isArray(t.history)||t.history.length>100)throw Error('سجل انتقال غير صالح.');if(new Set(t.annual.map(a=>a?.year)).size!==t.annual.length)throw Error('محطة سنوية مكررة.');for(const a of t.annual){field(a,'year','number');if(!Number.isInteger(a.year)||!years(p).includes(a.year))throw Error('محطة خارج أفق المشروع.');for(const k of ['target','actual'])field(a,k,'number',true);for(const k of ['milestone','evidence','actualSource','observation'])field(a,k,'string');}for(const h of t.history){field(h,'year','number',true);if(h.year!==null&&!Number.isInteger(h.year))throw Error('السنة التاريخية يجب أن تكون عددًا صحيحًا.');field(h,'value','number',true);field(h,'source','string');}}
 for(const e of p.enablers){for(const k of ['optionId','title','kind','action','control','owner','status','source','route','fallback'])field(e,k,'string');field(e,'dueYear','number',true);if(e.dueYear!==null&&!Number.isInteger(e.dueYear))throw Error('موعد الممكن يجب أن يكون سنة صحيحة.');if(!['legislation','authority','capability','culture','operating'].includes(e.kind)||!['keep','activate','amend','add','remove'].includes(e.action))throw Error('تصنيف ممكن غير صالح.');if(!['ready','pending','blocked','unknown'].includes(e.status)||!['internal','external','shared','unknown'].includes(e.control))throw Error('حالة ممكن غير صالحة.');}
 for(const i of p.initiatives){for(const k of ['optionId','transitionId','title','kind','owner','output','acceptance','capacity','budgetStatus','status'])field(i,k,'string');for(const k of ['startYear','endYear']){field(i,k,'number');if(!Number.isInteger(i[k]))throw Error('سنة المبادرة يجب أن تكون عددًا صحيحًا.');}if(!['learn','build','deliver'].includes(i.kind)||!['unconfirmed','confirmed'].includes(i.budgetStatus)||!['design','active','done'].includes(i.status))throw Error('تصنيف مبادرة غير صالح.');if(!Array.isArray(i.budget)||i.budget.length>16||!Array.isArray(i.dependsOn)||!Array.isArray(i.enablerIds))throw Error('قائمة مبادرة غير صالحة.');if(new Set(i.budget.map(b=>b?.year)).size!==i.budget.length)throw Error('ميزانية سنوية مكررة.');for(const b of i.budget){field(b,'year','number');if(!Number.isInteger(b.year)||!years(p).includes(b.year))throw Error('ميزانية خارج أفق المشروع.');field(b,'amount','number',true);if(num(b.amount)&&b.amount<0)throw Error('مبلغ سالب.');}if(![...i.dependsOn,...i.enablerIds].every(x=>typeof x==='string'))throw Error('روابط غير صالحة.');}
 for(const m of p.mandates){for(const k of ['title','relationship','source','contribution'])field(m,k,'string');if(!['mandatory','contribution','outside','unknown'].includes(m.relationship))throw Error('تصنيف تكليف غير صالح.');}
 if(new Set(p.funding.map(f=>f?.year)).size!==p.funding.length)throw Error('تمويل سنوي مكرر.');for(const f of p.funding){field(f,'year','number');if(!Number.isInteger(f.year)||!years(p).includes(f.year))throw Error('تمويل خارج أفق المشروع.');field(f,'available','number',true);if(num(f.available)&&f.available<0)throw Error('تمويل سالب.');}
 for(const l of p.log){if(!l||typeof l!=='object'||typeof l.at!=='string'||typeof l.action!=='string'||typeof l.path!=='string')throw Error('سجل محلي غير صالح.');}
 for(const k of ['weightRationale','reviewNote','createdAt','updatedAt'])field(p,k,'string');if(!Number.isInteger(p.revision)||p.revision<0)throw Error('نسخة غير صالحة.');p.reviewedRevision=null;return p;
}
function demo(){
 const p=blank();p.isDemo=true;
 Object.assign(p.institution,{name:'جامعة أفق — حالة افتراضية',sector:'جامعة حكومية افتراضية',mission:'تطوير المعرفة والخدمات التي تحسن تجربة الزائر وتخدم المجتمع المحلي.',beneficiaries:'الزوار والعاملون في الخدمات والطلاب وشركاء القطاع العام.',assets:'فريق متعدد التخصصات، شراكات تجريبية، وإمكانية دراسة تجربة الزائر ميدانيًا. جميعها افتراضات تعليمية.',context:'تختلف صلاحيات الجامعة ومصادر التمويل عن الجامعات المقارنة؛ يجب عدم نقل مستهدف خارجي قبل فحصه.',culture:'تُحتسب المساهمات داخل الأقسام منفردة؛ التعاون يتطلب اتفاقًا على الاعتراف بالمساهمات وتخصيص الوقت.',vision:'بحلول 2030، أن تثبت الجامعة حلولًا لتحسين تجربة الزائر يمكن لشركائها تطبيقها واستدامتها.',notDoing:'لن نوزع الاستثمار البحثي بالتساوي على كل المجالات، ولن نعد التوسع العددي غاية مستقلة.'});
 p.weightRationale='أوزان توضيحية اختيرت لإظهار المفاضلة، لا تمثل تقييمًا لجامعة أو اعتمادًا مؤسسيًا.';
 p.mandates=[{id:'m1',title:'الإسهام في أثر المعرفة على الخدمات',relationship:'contribution',source:'تكليف افتراضي لغرض العرض، لا وثيقة وزارة حقيقية.',contribution:'قيادة محور محدد يطابق رسالة الجامعة بدل نسخ جميع أهداف الجهة الأم.'}];
 const titles=['تركيز بحث تطبيقي في تجربة الزائر','منظومة معرفية استباقية لتجربة الزائر','توسيع جميع التخصصات بالتساوي'];
 p.options=titles.map((title,k)=>({...option(),id:'o'+(k+1),title,type:k===1?'moonshot':'differentiation',outcome:k===0?'حلول مختبرة يستخدمها شركاء محددون.':k===1?'إثبات نموذج جديد لتوقع المشكلات وتحسين الخدمة قبل وقوعها.':'تغطية أوسع دون اختيار قطاع مميز.',whyUs:k===2?'تحتاج الميزة الخاصة بالجهة إلى توضيح.':'موطئ القدم هو الشراكة والخبرة الميدانية المفترضتان في الحالة.',foothold:k===1?'اختبار أولي على خدمة واحدة؛ لا نفترض وجود القدرة الكاملة.':'',tradeoff:k===2?'موارد أقل متاحة للتركيز.':'تأجيل التوسع غير المرتبط بالمجال المختار.',owner:'فريق الاستراتيجية الافتراضي',decision:k===2?'defer':'select',decisionReason:k===2?'تأجيل إلى حين تقديم مبرر للميزة الخاصة.':k===1?'إدراج مسار تعلّم محدود قبل أي التزام بالتوسع.':'توظيف المقومات المفترضة في أثر محدد.',scores:Object.fromEntries(p.criteria.map((c,x)=>[c.id,{value:[[90,80,85,75],[90,95,95,65],[55,65,40,60]][k][x],note:'تقدير توضيحي للحالة الافتراضية؛ لا يمثل دليلًا ميدانيًا.'}]))}));
 p.references=[{id:'r1',name:'معيار تقييم داخلي تجريبي',kind:'internal',source:'معايير أعدت لهذه الحالة فقط؛ ليست اعتمادًا رسميًا.',purpose:'تعريف ما يعد حلًا مختبرًا وقابلًا للاستخدام.',context:'مناسب للنطاق التجريبي المحدد ولا يجوز نقله كمعيار وطني.',adaptation:'',status:'use'},{id:'r2',name:'جامعة مقارنة افتراضية',kind:'benchmark',source:'مثال تعليمي غير موثق؛ لا تُستخلص منه مستهدفات.',purpose:'فحص صلاحية استخدام نموذج تمويل فرق مشتركة.',context:'تختلف صلاحيات التمويل والمحاسبة.',adaptation:'يلزم تحديد ما يمكن نقله وما يتطلب قرارًا محليًا.',status:'unchecked'}];
 const t1=transition(p);Object.assign(t1,{id:'t1',optionId:'o1',referenceId:'r1',domain:'قدرة تشغيل الفرق المشتركة',current:'فريق واحد نفذ تجربة وفق بيانات افتراضية.',currentSource:'سجل تعليمي افتراضي 2026.',targetState:'6 فرق ذات قدرة مثبتة على تنفيذ مشروع مشترك وفق معيار الحالة.',kpi:'الفرق التي اجتازت اختبار العمل المشترك',unit:'فريق',baseline:1,target:6,owner:'مسؤول الشراكات الافتراضي',dataSource:'سجل اختبارات الفرق',history:[{year:2024,value:0,source:'مثال'},{year:2025,value:1,source:'مثال'},{year:2026,value:1,source:'مثال'}]});
 t1.annual=t1.annual.map((a,k)=>({...a,milestone:['تفعيل الوقت والصلاحيات واختبار فريقين','إثبات تكرار الأداء لأربعة فرق','توسيع تطبيق المعايير إلى خمسة فرق','استمرار ستة فرق دون دعم استثنائي'][k],target:[2,4,5,6][k],evidence:'محضر اختبار وفق معيار داخلي وتأكيد مالك الخدمة.',actual:k===0?1:null,actualSource:k===0?'قراءة افتراضية للتوضيح':'',observation:''}));
 const t2=transition(p);Object.assign(t2,{id:'t2',optionId:'o2',referenceId:'r1',domain:'إثبات فرضية المونشوت',direction:'qualitative',current:'خبرة وشراكة أولية؛ لا توجد قدرة تشغيلية كاملة.',currentSource:'افتراض تعليمي.',targetState:'حل قابل للاستخدام ثبتت فائدته ضمن نطاق متفق عليه.',kpi:'مرحلة تحقق الفرضية',unit:'وصف موثق',owner:'قائد المسار التجريبي',dataSource:'سجل التجارب وقرار المراجعة'});
 t2.annual=t2.annual.map((a,k)=>({...a,milestone:['اختبار قانوني ومحدود للفرضية','بناء قدرة أولية بشروط مشاركة واضحة','تجربة موسعة بعد الموافقات','تقييم الاستدامة وقرار التوسع أو التوقف'][k],evidence:'تقرير تجربة وقرار موثق؛ التوسع ليس تلقائيًا.'}));p.transitions=[t1,t2];
 p.enablers=[{...enabler(),id:'e1',optionId:'o1',title:'اعتماد وقت مشترك واحتساب المساهمات',kind:'operating',action:'amend',control:'internal',owner:'صاحب الصلاحية الداخلي — افتراضي',status:'pending',dueYear:2027,source:'إجراء داخلي افتراضي يحتاج تحققًا.',route:'مراجعة الإجراء مع أصحاب التنفيذ ثم اعتماد تعديل محدد.',fallback:'تجربة أصغر ضمن الوقت المصرح المتاح.'},{...enabler(),id:'e2',optionId:'o2',title:'موافقة مشاركة بيانات محددة',kind:'authority',action:'activate',control:'external',owner:'الجهة المالكة للبيانات — افتراضية',status:'unknown',dueYear:2028,source:'لا توجد موافقة فعلية في هذه الحالة.',route:'تحديد النطاق المسموح والحصول على القرار من صاحبه.',fallback:'استمرار التعلّم ببيانات اصطناعية وعدم استخدام بيانات مقيدة.'}];
 const make=(id,opt,tr,title,start,end,amounts,deps=[],ens=[])=>({...initiative(p),id,optionId:opt,transitionId:tr,title,startYear:start,endYear:end,kind:id==='i2'?'learn':'build',owner:'فريق تنفيذي افتراضي',output:id==='i2'?'تجربة ونتيجة تعلم موثقة':'قدرة مشتركة مجربة',acceptance:'تحقق الحالة المستهدفة وفق الدليل الموصوف، لا مجرد تسليم وثيقة.',capacity:'وقت وكفاءات مدخلة للتوضيح وتحتاج تقديرًا فعليًا.',budgetStatus:'unconfirmed',dependsOn:deps,enablerIds:ens,budget:years(p).map(year=>({year,amount:amounts[year]??null}))});
 p.initiatives=[make('i1','o1','t1','تهيئة واختبار الفرق المشتركة',2027,2028,{2027:200000,2028:300000},[],['e1']),make('i2','o2','t2','تجربة المونشوت ببيانات اصطناعية',2027,2028,{2027:150000,2028:250000}),make('i3','o2','t2','تجربة موسعة مشروطة بالموافقات',2029,2030,{2029:1000000,2030:1200000},['i2'],['e2'])];
 p.funding=years(p).map((year,k)=>({year,available:[500000,500000,1000000,1300000][k]}));return p;
}
const api={SCHEMA,clone,num,text,uid,years,blank,option,reference,transition,enabler,initiative,weightInfo,score,ranking,sensitivity,historySummary,progress,selected,selectedInitiatives,budgetSummary,cycles,check,syncYears,validateImport,demo};if(typeof module!=='undefined'&&module.exports)module.exports=api;root.Sultan=api;
})(typeof globalThis!=='undefined'?globalThis:this);
