/* SULTAN final programmatic upgrades: structured fields, dashboards, executive summary and client deliverables. */
(function(root){
'use strict';
const E=root.Sultan,T=root.SultanI18n.t;
if(!E||!root.SultanApp)return;
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const text=x=>typeof x==='string'&&x.trim().length>0;
const num=x=>typeof x==='number'&&Number.isFinite(x);
const fmt=x=>num(x)?Math.round(x).toLocaleString('en-US'):'—';
const section=()=>location.hash.slice(1)||'home';
function dl(name,data,type){const blob=data instanceof Blob?data:new Blob([data],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),3000);}
function opt(value,label,current){return `<option value="${esc(value)}" ${String(current)===String(value)?'selected':''}>${esc(label)}</option>`;}
function field(label,path,value,type='text',help='',extra=''){
 const id='fx_'+path.replace(/[^A-Za-z0-9_-]+/g,'_');
 let control='';
 if(type==='textarea')control=`<textarea id="${id}" data-path="${esc(path)}" rows="3" ${extra}>${esc(value??'')}</textarea>`;
 else if(type==='select')control=`<select id="${id}" data-path="${esc(path)}" ${extra}>${help}</select>`;
 else control=`<input id="${id}" data-path="${esc(path)}" type="${type}" value="${esc(value??'')}" ${extra}>`;
 const hint=type==='select'?'':help?`<span class="help">${esc(help)}</span>`:'';
 return `<label class="field final-field" for="${id}"><span>${esc(label)}</span>${control}${hint}<span class="field-error" hidden></span></label>`;
}
function touch(p){p.revision=(Number.isInteger(p.revision)?p.revision:0)+1;p.updatedAt=new Date().toISOString();p.reviewedRevision=null;return p;}
function saveProject(p,target){touch(p);root.SultanApp.setProject(p);if(target)root.SultanApp.navigate(target);}

/* E4: one consistency pass per edit state, not once per navigation button. */
(function(){const raw=E.check;let key='',cached=[];E.check=function(p){const k=[p?.revision,p?.updatedAt,p?.options?.length,p?.transitions?.length,p?.initiatives?.length].join('|');if(k===key)return cached.slice();key=k;cached=raw(p);return cached.slice();};})();

function renderRecovery(){
 const r=root.SultanRecovery;if(!r?.pending)return;
 let b=document.querySelector('.recovery-lock');if(!b){b=document.createElement('section');b.className='recovery-lock';b.setAttribute('role','alert');document.body.prepend(b);}
 b.innerHTML=`<div><b>${esc(T('recoveryTitle'))}</b><p>${esc(T('recoveryMessage'))}</p><small>${esc(T('recoveryLocked'))}</small></div><div class="recovery-actions"><button type="button" class="btn" data-final-action="recovery-download">${esc(T('recoveryDownload'))}</button><button type="button" class="btn primary" data-final-action="recovery-new">${esc(T('recoveryNew'))}</button></div>`;
 document.querySelectorAll('.shell input,.shell textarea,.shell select,.shell button').forEach(el=>el.disabled=true);
 const s=document.getElementById('saveStatus');if(s)s.textContent=T('recoveryLocked');
}
function renderVersion(){const f=document.querySelector('.sidefoot');if(f&&!f.querySelector('.final-version'))f.insertAdjacentHTML('afterbegin',`<span class="final-version">${esc(T('versionLabel'))} ${esc(root.SULTAN_VERSION||'0.7.4')}</span><br>`);}

function renderIdentity(){
 if(section()!=='identity')return;const p=root.SultanApp.getProject(),content=document.getElementById('content'),card=content?.querySelector('article.card');if(!card)return;
 if(!card.querySelector('[data-path="institution.liabilities"]')){const a=card.querySelector('[data-path="institution.assets"]')?.closest('.field'),h=field(T('liabilities'),'institution.liabilities',p.institution.liabilities,'textarea',T('liabilitiesHelp'));if(a)a.insertAdjacentHTML('afterend',h);else card.insertAdjacentHTML('beforeend',h);}
 const empty=!text(p.institution.name)&&!text(p.institution.mission)&&!text(p.institution.beneficiaries)&&!text(p.institution.vision);
 if(!empty||card.querySelector('.identity-starter'))return;
 const starter=document.createElement('div');starter.className='identity-starter';starter.innerHTML=`<h3>${esc(T('identityStarter'))}</h3><div class="starter-grid"></div>`;const g=starter.querySelector('.starter-grid');
 ['institution.mission','institution.beneficiaries','institution.endYear'].forEach(path=>{const f=card.querySelector(`[data-path="${path}"]`)?.closest('.field');if(f)g.append(f);});
 const more=document.createElement('details');more.className='identity-more';more.innerHTML=`<summary>${esc(T('identityMore'))}</summary><div class="identity-more-body"></div>`;const body=more.querySelector('.identity-more-body');
 Array.from(card.querySelectorAll(':scope > .grid2')).forEach(gr=>{while(gr.firstChild)body.append(gr.firstChild);gr.remove();});card.prepend(more);card.prepend(starter);
}

function assumptionHtml(o,i){
 let out=`<section class="assumption-register final-feature"><div class="feature-head"><h3>${esc(T('assumptionRegister2'))}</h3><button type="button" class="btn small" data-final-action="assumption-add" data-option="${i}">${esc(T('assumptionAdd'))}</button></div>`;
 (o.assumptions||[]).forEach((a,j)=>{out+=`<details open class="assumption-item"><summary>${esc(a.text||T('assumptionText'))}</summary><div class="grid2">${field(T('assumptionText'),`options.${i}.assumptions.${j}.text`,a.text,'textarea')}${field(T('assumptionDuration'),`options.${i}.assumptions.${j}.expectedPersistence`,a.expectedPersistence)}${field(T('assumptionOwner'),`options.${i}.assumptions.${j}.owner`,a.owner)}${field(T('assumptionTestDate'),`options.${i}.assumptions.${j}.testDate`,a.testDate,'date')}${field(T('assumptionEvidence'),`options.${i}.assumptions.${j}.testEvidence`,a.testEvidence,'textarea')}${field(T('assumptionFailure'),`options.${i}.assumptions.${j}.failureImpact`,a.failureImpact,'textarea')}</div><button type="button" class="btn small danger" data-final-action="assumption-remove" data-option="${i}" data-assumption="${j}">×</button></details>`;});
 return out+'</section>';
}
function renderChoices(){
 if(section()!=='choices')return;const p=root.SultanApp.getProject(),content=document.getElementById('content');if(!content)return;const cards=Array.from(content.querySelectorAll('article.card')).slice(0,p.options.length);
 cards.forEach((card,i)=>{const o=p.options[i],sel=card.querySelector(`[data-path="options.${i}.type"]`);if(sel&&!sel.querySelector('option[value="divest"]'))sel.insertAdjacentHTML('beforeend',opt('divest',T('divest'),o.type));if(o.type==='requirement'&&!card.querySelector('.requirement-note'))card.insertAdjacentHTML('afterbegin',`<p class="hint requirement-note">${esc(T('requirementRankNote'))}</p>`);if(card.querySelector('.final-choice-fields'))return;
  let h='';
  if(o.type==='moonshot')h+=field(T('moonshotStopEvidence'),`options.${i}.stopEvidence`,o.stopEvidence,'textarea',T('moonshotStopEvidenceHelp'));
  if(o.type==='divest'){h+=`<div class="final-feature"><p class="hint">${esc(T('divestHelp'))}</p><div class="grid2">`;h+=field(T('divestStop'),`options.${i}.divestStop`,o.divestStop,'textarea');h+=field(T('divestResources'),`options.${i}.releasedResources`,o.releasedResources,'number',T('releasedResources'),'min="0" step="any"');h+=field(T('divestRedeploy'),`options.${i}.redeployTo`,o.redeployTo,'textarea');h+=field(T('divestEvidence'),`options.${i}.divestEvidence`,o.divestEvidence,'textarea');h+=field(T('divestImpact'),`options.${i}.divestImpact`,o.divestImpact,'textarea');h+='</div></div>';}
  if(o.type!=='requirement')h+=`<div class="grid2">${field(T('riskSource'),`options.${i}.riskSource`,o.riskSource,'textarea')}${field(T('riskDate'),`options.${i}.riskDate`,o.riskDate,'date')}</div>`;
  h+=assumptionHtml(o,i);const box=document.createElement('div');box.className='final-choice-fields';box.innerHTML=h;card.append(box);
 });
}

function renderReferences(){
 if(section()!=='references')return;const p=root.SultanApp.getProject(),content=document.getElementById('content');if(!content)return;
 const heading=content.querySelector('.heading');if(heading&&!content.querySelector('.route-initiative-note'))heading.insertAdjacentHTML('afterend',`<p class="hint route-initiative-note">${esc(T('routeVsInitiative'))}</p>`);
 p.transitions.forEach((t,i)=>{const sel=content.querySelector(`[data-path="transitions.${i}.direction"]`);if(sel&&!sel.querySelector('option[value="delta"]'))sel.insertAdjacentHTML('beforeend',opt('delta',T('delta'),t.direction));const card=sel?.closest('article.card');if(!card||card.querySelector('.final-transition-fields'))return;
  const trackOptions=opt('outcome',T('dashboardProgress'),t.trackType)+opt('maturity',T('maturity'),t.trackType),indOptions=opt('performance',T('indicatorPerformance'),t.indicatorType)+opt('risk',T('indicatorRisk'),t.indicatorType);
  let h=`<div class="grid3">${field(T('maturity'),`transitions.${i}.trackType`,t.trackType,'select',trackOptions)}${field(T('maturityFamily'),`transitions.${i}.maturityFamily`,t.maturityFamily)}${field(T('indicatorType'),`transitions.${i}.indicatorType`,t.indicatorType,'select',indOptions)}</div>`;
  if(t.direction==='delta'&&num(t.baseline)&&num(t.target))h+=`<p class="hint">${esc(T('deltaAbsolute'))}: <b>${fmt(t.baseline+t.target)}</b> ${esc(t.unit||'')}</p>`;
  if(t.trackType==='maturity')h+=`<p class="hint">${esc(T('dashboardMaturity'))}: ${fmt(t.baseline)} → ${fmt(t.target)} / 5</p>`;
  const box=document.createElement('div');box.className='final-transition-fields final-feature';box.innerHTML=h;card.append(box);
 });
}
function renderRoadmap(){
 if(section()!=='roadmap')return;const p=root.SultanApp.getProject(),content=document.getElementById('content');if(!content)return;
 p.initiatives.forEach((i,ix)=>{if(i.kind!=='learn')return;i.budget.forEach((b,bx)=>{if(b.year<i.startYear||b.year>i.endYear)return;const a=content.querySelector(`[data-path="initiatives.${ix}.budget.${bx}.amount"]`),host=a?.closest('.field');if(!host||host.nextElementSibling?.classList?.contains('release-evidence-field'))return;const h=field(T('releaseEvidence'),`initiatives.${ix}.budget.${bx}.releaseEvidence`,b.releaseEvidence,'textarea').replace('final-field','final-field release-evidence-field');host.insertAdjacentHTML('afterend',h);});});
}

function renderCollaboration(){
 const s=section();if(['home','about'].includes(s))return;const p=root.SultanApp.getProject(),content=document.getElementById('content');if(!content||content.querySelector('.collaboration-bar'))return;const owner=p.collaboration?.owners?.[s]||'';const bar=document.createElement('section');bar.className='collaboration-bar noPrint';bar.innerHTML=`<div><b>${esc(T('workshopOwner'))}</b><input type="text" data-final-owner="${esc(s)}" value="${esc(owner)}" placeholder="${esc(T('workshopAssign'))}"></div><div class="contribution-entry"><input type="text" data-final-contributor placeholder="${esc(T('workshopContributor'))}"><input type="text" data-final-note placeholder="${esc(T('workshopContribution'))}"><button type="button" class="btn small" data-final-action="contribution-add" data-section="${esc(s)}">+</button></div>`;content.prepend(bar);
}

function metrics(p){const selected=new Set(p.options.filter(o=>o.decision==='select').map(o=>o.id)),ens=p.enablers.filter(e=>selected.has(e.optionId)),pending=ens.filter(e=>e.status!=='ready'),external=pending.filter(e=>['external','shared','unknown'].includes(e.control)),due=pending.filter(e=>Number.isInteger(e.dueYear)).map(e=>e.dueYear),blocked=new Set(ens.filter(e=>e.status==='blocked').map(e=>e.optionId)),gap=E.budgetSummary(p).reduce((s,b)=>s+(num(b.gap)?b.gap:0),0);return {decisions:pending.length,external:external.length,nextDue:due.length?Math.min(...due):null,blocked:blocked.size,gap};}
function summaryHtml(p){const m=metrics(p);return `<section class="executive-summary"><h2>${esc(T('executiveSummary'))}</h2><div class="executive-grid"><div><span>${esc(T('summaryDecisions'))}</span><strong>${m.decisions}</strong></div><div><span>${esc(T('summaryExternal'))}</span><strong>${m.external}</strong></div><div><span>${esc(T('summaryNextDue'))}</span><strong>${m.nextDue??'—'}</strong></div><div><span>${esc(T('summaryBlocked'))}</span><strong>${m.blocked}</strong></div><div><span>${esc(T('summaryFundingGap'))}</span><strong>${fmt(m.gap)}</strong></div></div><p class="report-principle">${esc(T('noSingleScore'))}</p><p><b>${esc(T('documentNumber'))} ${p.documentNumber}</b> · ${esc(T('editRevision'))} ${p.revision}</p></section>`;}
function extensionReport(p){
 const chunks=[];if(text(p.institution.liabilities))chunks.push(`<h3>${esc(T('liabilities'))}</h3><p>${esc(p.institution.liabilities)}</p>`);
 p.options.forEach(o=>{if(o.type==='divest'){chunks.push(`<h3>${esc(o.title)} · ${esc(T('divest'))}</h3><dl><dt>${esc(T('divestStop'))}</dt><dd>${esc(o.divestStop)}</dd><dt>${esc(T('divestResources'))}</dt><dd>${fmt(o.releasedResources)}</dd><dt>${esc(T('divestRedeploy'))}</dt><dd>${esc(o.redeployTo)}</dd><dt>${esc(T('divestEvidence'))}</dt><dd>${esc(o.divestEvidence)}</dd><dt>${esc(T('divestImpact'))}</dt><dd>${esc(o.divestImpact)}</dd></dl>`);}if(o.type==='moonshot'&&text(o.stopEvidence))chunks.push(`<h3>${esc(o.title)} · ${esc(T('moonshotStopEvidence'))}</h3><p>${esc(o.stopEvidence)}</p>`);if(Array.isArray(o.assumptions)&&o.assumptions.length){const rows=o.assumptions.map(a=>`<dl><dt>${esc(T('assumptionText'))}</dt><dd>${esc(a.text)}</dd><dt>${esc(T('assumptionDuration'))}</dt><dd>${esc(a.expectedPersistence)}</dd><dt>${esc(T('assumptionOwner'))}</dt><dd>${esc(a.owner)}</dd><dt>${esc(T('assumptionTestDate'))}</dt><dd>${esc(a.testDate)}</dd><dt>${esc(T('assumptionEvidence'))}</dt><dd>${esc(a.testEvidence)}</dd><dt>${esc(T('assumptionFailure'))}</dt><dd>${esc(a.failureImpact)}</dd></dl>`).join('');chunks.push(`<h3>${esc(o.title)} · ${esc(T('assumptionRegister2'))}</h3>${rows}`);}});
 return chunks.length?`<section class="extension-report"><h2>SULTAN decision extensions</h2>${chunks.join('')}</section>`:'';
}
function collaborationReport(p){const owners=p.collaboration?.owners||{},rows=p.collaboration?.contributions||[];if(!rows.length&&!Object.values(owners).some(text))return '';const ownerRows=Object.entries(owners).filter(([,v])=>text(v)).map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join('');const log=rows.map(r=>`<p><b>${esc(r.name||'—')}</b> · ${esc(r.section)} · ${esc(r.at)}<br>${esc(r.note)}</p>`).join('');return `<section class="collaboration-report"><h2>${esc(T('workshopLog'))}</h2><dl>${ownerRows}</dl>${log}</section>`;}
const baseReport=root.SultanApp.getReport.bind(root.SultanApp);
root.SultanApp.getReport=function(){const p=root.SultanApp.getProject(),body=baseReport(),extra=summaryHtml(p)+extensionReport(p)+collaborationReport(p),i=body.indexOf('</header>');return i>=0?body.slice(0,i+9)+extra+body.slice(i+9):extra+body;};

function trackSvg(t,p){const ys=E.years(p),vals=[];if(num(t.baseline))vals.push(t.baseline);t.annual.forEach(a=>{const v=t.direction==='delta'&&num(t.baseline)&&num(a.target)?t.baseline+a.target:a.target;if(num(v))vals.push(v);if(num(a.actual))vals.push(a.actual);});if(!vals.length)return `<p>${esc(T('noData'))}</p>`;const mn=Math.min(...vals),mx=Math.max(...vals),span=mx-mn||1,w=620,h=150,x=i=>30+i*((w-60)/Math.max(1,ys.length)),y=v=>h-25-((v-mn)/span)*(h-50),points=a=>a.map(q=>q.join(',')).join(' ');const target=[],actual=[];if(num(t.baseline)){target.push([x(0),y(t.baseline)]);actual.push([x(0),y(t.baseline)]);}t.annual.forEach((a,i)=>{const v=t.direction==='delta'&&num(t.baseline)&&num(a.target)?t.baseline+a.target:a.target;if(num(v))target.push([x(i+1),y(v)]);if(num(a.actual))actual.push([x(i+1),y(a.actual)]);});return `<svg viewBox="0 0 ${w} ${h}" class="track-svg"><polyline points="${points(target)}" class="target-line"></polyline>${actual.length>1?`<polyline points="${points(actual)}" class="actual-line"></polyline>`:''}${ys.map((v,i)=>`<text x="${x(i+1)}" y="145" text-anchor="middle">${v}</text>`).join('')}</svg>`;}
function fundingPanel(p){const rows=E.budgetSummary(p),mx=Math.max(1,...rows.flatMap(r=>[r.declared||0,r.available||0]));return `<div class="funding-bars">${rows.map(r=>`<div class="funding-year"><b>${r.year}</b><span class="bar declared" style="--w:${Math.round((r.declared/mx)*100)}%"><i>${fmt(r.declared)}</i></span><span class="bar available" style="--w:${Math.round(((r.available||0)/mx)*100)}%"><i>${r.available==null?'—':fmt(r.available)}</i></span><small>${r.unknown?`${r.unknown} × ${esc(T('noReading'))}`:''}${num(r.gap)&&r.gap>0?` · ${esc(T('summaryFundingGap'))}: ${fmt(r.gap)}`:''}</small></div>`).join('')}</div>`;}
function authorityPanel(p){const selected=new Set(p.options.filter(o=>o.decision==='select').map(o=>o.id)),ens=p.enablers.filter(e=>selected.has(e.optionId)),c={ready:0,pending:0,blocked:0,unknown:0};ens.forEach(e=>{if(e.status==='ready')c.ready++;else if(e.status==='pending')c.pending++;else if(e.status==='blocked')c.blocked++;else c.unknown++;});const n=Math.max(1,ens.length),due=ens.filter(e=>e.status!=='ready'&&Number.isInteger(e.dueYear)).map(e=>e.dueYear);return `<div class="authority-stack">${Object.entries(c).map(([k,v])=>`<span class="${k}" style="--w:${v/n*100}%" title="${k}: ${v}"></span>`).join('')}</div><p>${esc(T('summaryNextDue'))}: <b>${due.length?Math.min(...due):'—'}</b></p>`;}
function timelinePanel(p){const ys=E.years(p),items=E.selectedInitiatives(p);return `<div class="dashboard-timeline" style="--years:${ys.length}"><div></div>${ys.map(y=>`<b>${y}</b>`).join('')}${items.map(i=>`<span>${esc(i.title)}</span>${ys.map(y=>`<i class="${y>=i.startYear&&y<=i.endYear?'active':''}"></i>`).join('')}`).join('')}</div>`;}
function statusFor(t){const a=[...t.annual].reverse().find(r=>num(r.actual));return a?E.indicatorStatus(t,a):'noReading';}
function renderDashboard(){
 if(section()!=='review')return;const content=document.getElementById('content');if(!content||content.querySelector('.final-dashboard'))return;const p=root.SultanApp.getProject(),selected=new Set(p.options.filter(o=>o.decision==='select').map(o=>o.id)),trs=p.transitions.filter(t=>selected.has(t.optionId)),outcome=trs.filter(t=>t.trackType!=='maturity'&&t.indicatorType!=='risk'),maturity=trs.filter(t=>t.trackType==='maturity'),risk=trs.filter(t=>t.indicatorType==='risk');
 let h=`<h2>${esc(T('dashboardTitle'))}</h2><p class="muted">${esc(T('dashboardIntro'))}</p><div class="dashboard-grid"><section><h3>${esc(T('dashboardProgress'))}</h3>`;h+=outcome.length?outcome.map(t=>`<div class="track-card"><div><b>${esc(t.kpi||t.domain)}</b><span class="status ${statusFor(t)}">${esc(T(statusFor(t)))}</span></div>${trackSvg(t,p)}</div>`).join(''):`<p>${esc(T('noData'))}</p>`;h+=`</section><section><h3>${esc(T('dashboardFunding'))}</h3>${fundingPanel(p)}</section><section><h3>${esc(T('dashboardAuthority'))}</h3>${authorityPanel(p)}</section><section><h3>${esc(T('dashboardTimeline'))}</h3>${timelinePanel(p)}</section>`;if(maturity.length)h+=`<section><h3>${esc(T('dashboardMaturity'))}</h3>${maturity.map(t=>`<p><b>${esc(t.maturityFamily||t.domain)}</b> · ${fmt(t.baseline)} → ${fmt(t.target)} / 5</p>`).join('')}</section>`;if(risk.length)h+=`<section><h3>${esc(T('dashboardRisk'))}</h3>${risk.map(t=>`<p><b>${esc(t.kpi||t.domain)}</b> <span class="status ${statusFor(t)}">${esc(T(statusFor(t)))}</span></p>`).join('')}</section>`;h+='</div>';const card=document.createElement('article');card.className='card final-dashboard';card.innerHTML=h;const heading=content.querySelector('.heading');if(heading)heading.insertAdjacentElement('afterend',card);else content.prepend(card);content.querySelectorAll('.reportPreview h1').forEach(old=>{const n=document.createElement('h2');n.innerHTML=old.innerHTML;old.replaceWith(n);});
}
function renderExecutive(){if(section()!=='review')return;const content=document.getElementById('content');if(!content||content.querySelector('.review-executive'))return;const c=document.createElement('article');c.className='card review-executive';c.innerHTML=summaryHtml(root.SultanApp.getProject());const d=content.querySelector('.final-dashboard');if(d)d.insertAdjacentElement('beforebegin',c);else content.prepend(c);}

function reportDoc(body,title){return `<!doctype html><html lang="${root.SultanI18n.language}" dir="${root.SultanI18n.direction}"><meta charset="utf-8"><title>${esc(title)}</title><style>body{font:16px/1.8 Tahoma,Arial,sans-serif;color:#0b2d63;margin:28px auto;max-width:1080px;padding:26px}h1,h2,h3{color:#0b2d63}header{border-bottom:3px solid #caa85e}table{width:100%;border-collapse:collapse}td,th{padding:8px;border:1px solid #ddd;text-align:start;vertical-align:top}dl{display:grid;grid-template-columns:180px 1fr;gap:7px 14px}dt{font-weight:bold}dd{margin:0}.executive-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:10px}.executive-grid>div{border:1px solid #ddd;padding:10px}.report-principle{padding:10px;background:#f5f0e5;border-inline-start:4px solid #caa85e}</style><body>${body}</body></html>`;}
function escalationReport(p){const rows=E.authorityEscalationItems?E.authorityEscalationItems(p):[];return `<article><header><h1>${esc(T('exportEscalation'))}</h1><p>${esc(p.institution.name||'SULTAN')}</p></header>${summaryHtml(p)}<table><thead><tr><th>${esc(T('summaryExternal'))}</th><th>${esc(T('workshopOwner'))}</th><th>${esc(T('summaryNextDue'))}</th><th>Route</th><th>Fallback</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.choice)} — ${esc(r.title)}</td><td>${esc(r.owner||'—')}</td><td>${r.dueYear??'—'}</td><td>${esc(r.route||'—')}</td><td>${esc(r.fallback||'—')}</td></tr>`).join('')}</tbody></table></article>`;}
function bodyFor(kind,p){return kind==='escalation'?escalationReport(p):root.SultanApp.getReport();}
function labelFor(kind){return kind==='strategy'?T('exportStrategy'):kind==='leadership'?T('exportLeadership'):T('exportEscalation');}
function nextDoc(){const p=root.SultanApp.getProject();E.nextDocumentNumber(p);touch(p);root.SultanApp.setProject(p);return root.SultanApp.getProject();}
function exportHtml(kind){const p=nextDoc();dl(`SULTAN_${kind}_D${p.documentNumber}.html`,reportDoc(bodyFor(kind,p),labelFor(kind)),'text/html;charset=utf-8');}
function exportWord(kind){const p=nextDoc(),doc=reportDoc(bodyFor(kind,p),labelFor(kind)).replace('<html','<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word"');dl(`SULTAN_${kind}_D${p.documentNumber}.doc`,doc,'application/msword;charset=utf-8');}

/* True downloadable PDF: browser shapes Arabic, each page is rasterized, then embedded as JPEG in a compact PDF. */
const enc=s=>new TextEncoder().encode(s);
function join(parts){const size=parts.reduce((n,p)=>n+p.length,0),out=new Uint8Array(size);let at=0;parts.forEach(p=>{out.set(p,at);at+=p.length;});return out;}
function b64bytes(url){const s=atob(url.split(',')[1]),a=new Uint8Array(s.length);for(let i=0;i<s.length;i++)a[i]=s.charCodeAt(i);return a;}
function pdfBlob(images){const objs=[],pages=[],imgs=[],contents=[];let id=3;images.forEach(()=>{pages.push(id++);imgs.push(id++);contents.push(id++);});objs[1]=enc('<< /Type /Catalog /Pages 2 0 R >>');objs[2]=enc(`<< /Type /Pages /Count ${images.length} /Kids [${pages.map(x=>x+' 0 R').join(' ')}] >>`);images.forEach((im,i)=>{const stream=`q\n595 0 0 842 0 0 cm\n/Im${i} Do\nQ\n`;objs[pages[i]]=enc(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /XObject << /Im${i} ${imgs[i]} 0 R >> >> /Contents ${contents[i]} 0 R >>`);objs[imgs[i]]=join([enc(`<< /Type /XObject /Subtype /Image /Width ${im.w} /Height ${im.h} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${im.data.length} >>\nstream\n`),im.data,enc('\nendstream')]);objs[contents[i]]=enc(`<< /Length ${stream.length} >>\nstream\n${stream}endstream`);});const parts=[enc('%PDF-1.4\n')],offset=[0,0];let pos=parts[0].length;for(let i=1;i<objs.length;i++){offset[i]=pos;const a=enc(`${i} 0 obj\n`),b=enc('\nendobj\n');parts.push(a,objs[i],b);pos+=a.length+objs[i].length+b.length;}const xref=pos;let x=`xref\n0 ${objs.length}\n0000000000 65535 f \n`;for(let i=1;i<objs.length;i++)x+=String(offset[i]).padStart(10,'0')+' 00000 n \n';x+=`trailer\n<< /Size ${objs.length} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;parts.push(enc(x));return new Blob(parts,{type:'application/pdf'});}
async function pageImages(body,title){const host=document.createElement('div');host.className='pdf-render-host';host.innerHTML=body;document.body.append(host);await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));const w=794,ph=1123,total=Math.max(ph,host.scrollHeight),n=Math.ceil(total/ph),html=host.innerHTML,images=[];for(let i=0;i<n;i++){const y=-i*ph,svg=`<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${ph}"><foreignObject width="100%" height="100%"><div xmlns="http://www.w3.org/1999/xhtml" style="position:relative;width:${w}px;height:${ph}px;overflow:hidden;background:white"><style>body{margin:0;font:16px/1.8 Tahoma,Arial,sans-serif;color:#0b2d63}h1,h2,h3{color:#0b2d63}table{width:100%;border-collapse:collapse}td,th{border:1px solid #ddd;padding:8px}dl{display:grid;grid-template-columns:180px 1fr;gap:6px 12px}.executive-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:8px}</style><div style="width:${w}px;transform:translateY(${y}px)">${html}</div></div></foreignObject></svg>`,url=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml;charset=utf-8'})),img=new Image();await new Promise((ok,bad)=>{img.onload=ok;img.onerror=bad;img.src=url;});const c=document.createElement('canvas');c.width=Math.round(w*1.35);c.height=Math.round(ph*1.35);const ctx=c.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(img,0,0,c.width,c.height);URL.revokeObjectURL(url);images.push({data:b64bytes(c.toDataURL('image/jpeg',.88)),w:c.width,h:c.height});}host.remove();return images;}
async function exportPdf(kind,b){const p=nextDoc();if(b){b.disabled=true;b.dataset.label=b.textContent;b.textContent='…';}try{const images=await pageImages(bodyFor(kind,p),labelFor(kind));dl(`SULTAN_${kind}_D${p.documentNumber}.pdf`,pdfBlob(images),'application/pdf');}catch(err){console.error(err);alert(String(err.message||err));}finally{if(b){b.disabled=false;b.textContent=b.dataset.label||T('exportPdf');}}}
function renderExport(){const menu=document.querySelector('.export-menu-panel');if(!menu||menu.querySelector('.final-deliverables'))return;const box=document.createElement('div');box.className='final-deliverables';let h='<b>Client deliverables</b>';['strategy','leadership','escalation'].forEach(k=>{h+=`<div class="deliverable-row"><span>${esc(labelFor(k))}</span><button class="btn small" type="button" data-final-export="${k}" data-format="html">${esc(T('exportHtml'))}</button><button class="btn small" type="button" data-final-export="${k}" data-format="word">${esc(T('exportWord'))}</button><button class="btn small" type="button" data-final-export="${k}" data-format="pdf">${esc(T('exportPdf'))}</button></div>`;});box.innerHTML=h;menu.append(box);}

const sectionMap={identity:['institution','mandates'],choices:['options'],references:['references','transitions'],priorities:['criteria','weightRationale'],enablers:['enablers'],roadmap:['initiatives','funding'],review:['reviewNote']};
function exportSection(){const s=section(),keys=sectionMap[s];if(!keys)return;const p=root.SultanApp.getProject(),x={kind:'sultan.section.v2',section:s,baseSchema:p.schema,exportedAt:new Date().toISOString(),owner:p.collaboration?.owners?.[s]||'',contributions:(p.collaboration?.contributions||[]).filter(r=>r.section===s),data:{}};keys.forEach(k=>x.data[k]=p[k]);dl(`SULTAN_${s}_section_v2.json`,JSON.stringify(x,null,2),'application/json;charset=utf-8');}
function importSection(){const input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.onchange=()=>{const f=input.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(x.kind!=='sultan.section.v2'||!sectionMap[x.section])throw Error('Invalid SULTAN section file.');const p=root.SultanApp.getProject();sectionMap[x.section].forEach(k=>{if(Object.prototype.hasOwnProperty.call(x.data||{},k))p[k]=x.data[k];});p.collaboration=p.collaboration||{owners:{},contributions:[]};p.collaboration.owners[x.section]=String(x.owner||'');p.collaboration.contributions=[...(p.collaboration.contributions||[]),...(x.contributions||[])].slice(-250);saveProject(p,x.section);}catch(err){alert(String(err.message||err));}};r.readAsText(f);};input.click();}

/* E5: use the render snapshot instead of cloning project state for every range-input pixel. */
document.addEventListener('input',e=>{const s=e.target.closest('[data-sensitivity]');if(!s)return;e.stopImmediatePropagation();const card=s.closest('.break-even-card');if(!card)return;const p=card.__finalProject||root.SultanApp.getProject();card.__finalProject=p;s.nextElementSibling.textContent=s.value+'%';const rows=E.rankingAt(p,s.dataset.sensitivity,Number(s.value)),box=card.querySelector('.sensitivity-preview');if(box)box.innerHTML=rows.slice(0,5).map((x,i)=>`<div class="rank"><span class="ranknum">${i+1}</span><b>${esc(x.title)}</b><strong>${fmt(x.value)}</strong></div>`).join('');},true);

document.addEventListener('change',e=>{const o=e.target.closest('[data-final-owner]');if(!o)return;const p=root.SultanApp.getProject();p.collaboration.owners[o.dataset.finalOwner]=o.value;saveProject(p,o.dataset.finalOwner);});
document.addEventListener('click',e=>{
 const b=e.target.closest('[data-final-action],[data-final-export],[data-exec="section-export"],[data-exec="section-import"],[data-action="report"],[data-exec="leadership-report"],[data-exec="escalation"],[data-action="reviewed"]');if(!b)return;
 if(b.matches('[data-exec="section-export"]')){e.preventDefault();e.stopImmediatePropagation();exportSection();return;}
 if(b.matches('[data-exec="section-import"]')){e.preventDefault();e.stopImmediatePropagation();importSection();return;}
 if(b.matches('[data-action="report"]')){e.preventDefault();e.stopImmediatePropagation();exportHtml('strategy');return;}
 if(b.matches('[data-exec="leadership-report"]')){e.preventDefault();e.stopImmediatePropagation();exportHtml('leadership');return;}
 if(b.matches('[data-exec="escalation"]')){e.preventDefault();e.stopImmediatePropagation();exportHtml('escalation');return;}
 if(b.matches('[data-action="reviewed"]')){e.preventDefault();e.stopImmediatePropagation();const p=root.SultanApp.getProject();E.nextDocumentNumber(p);touch(p);p.reviewedRevision=p.revision;root.SultanApp.setProject(p);return;}
 const a=b.dataset.finalAction;
 if(a==='recovery-download'){root.SultanRecovery?.download();return;}
 if(a==='recovery-new'){root.SultanRecovery?.startNew();location.reload();return;}
 if(a==='assumption-add'){const p=root.SultanApp.getProject(),i=Number(b.dataset.option);p.options[i].assumptions=p.options[i].assumptions||[];p.options[i].assumptions.push({id:E.uid('asm'),text:'',expectedPersistence:'',owner:'',testDate:'',testEvidence:'',failureImpact:''});saveProject(p,'choices');return;}
 if(a==='assumption-remove'){const p=root.SultanApp.getProject(),i=Number(b.dataset.option),j=Number(b.dataset.assumption);p.options[i].assumptions.splice(j,1);saveProject(p,'choices');return;}
 if(a==='contribution-add'){const p=root.SultanApp.getProject(),bar=b.closest('.collaboration-bar'),name=bar.querySelector('[data-final-contributor]').value,note=bar.querySelector('[data-final-note]').value;if(!text(name)&&!text(note))return;E.recordContribution(p,b.dataset.section,name,note);saveProject(p,b.dataset.section);return;}
 if(b.dataset.finalExport){e.preventDefault();e.stopImmediatePropagation();if(b.dataset.format==='html')exportHtml(b.dataset.finalExport);else if(b.dataset.format==='word')exportWord(b.dataset.finalExport);else exportPdf(b.dataset.finalExport,b);}
},true);

function afterRender(){setTimeout(()=>{renderVersion();renderRecovery();renderIdentity();renderChoices();renderReferences();renderRoadmap();renderCollaboration();renderDashboard();renderExecutive();renderExport();const c=document.querySelector('.break-even-card');if(c)c.__finalProject=root.SultanApp.getProject();},0);}
document.addEventListener('sultan:render',afterRender);afterRender();
})(globalThis);
