/* General templates, not a catalogue of verified international regulations. */
(function(root){
'use strict';
const L=root.SultanLibrary;if(!L)return;
const t=(ar,en)=>({ar,en});
const outcomes={edu:t('تحسين نتائج التعلم الموثقة','Improve evidenced learning outcomes'),highered:t('تعزيز الأثر التعليمي والبحثي المثبت','Improve evidenced educational and research impact'),health:t('تحسين نتائج الخدمة الصحية وسلامتها','Improve health service outcomes and safety'),gov:t('تحسين نتائج الخدمة العامة','Improve public service outcomes'),nonprofit:t('زيادة الأثر المثبت للمستفيدين','Increase evidenced beneficiary outcomes'),tech:t('بناء خدمات متكررة ذات قيمة مثبتة','Build recurring services with evidenced value')};
const G={verifiedOn:'general-templates',pick:L.pick};
G.sectors=L.sectors.map(s=>({id:s.id,name:s.name,short:t('قوالب عامة تُكيّف مع الدولة والجهة','General templates to adapt to the country and institution'),types:s.types,regulator:t('يحددها المستخدم بحسب الدولة','To be identified for the selected country'),templates:{context:t('حدد النطاق التنظيمي والتمويل والتكليفات الفعلية؛ لا تُفترض دولة أو جهة تنظيمية.','Identify the applicable jurisdiction, funding and mandates; no country or regulator is assumed.')},programs:[],regulations:[],indicators:[{id:'verified-outcome',scope:'institutional',direction:'up',name:t('نسبة الحالات التي حققت النتيجة المتفق عليها','Share of cases achieving the agreed outcome'),unit:t('٪','%'),frequency:t('ربع سنوي','Quarterly'),dataSource:t('سجلات قياس موثقة ومراجعة مستقلة','Documented measurement records and independent review'),domain:t('الأثر','Impact'),refs:[]}],goals:[{id:'verified-outcome',group:'quality',type:'differentiation',kpi:'verified-outcome',refs:[],programs:[],title:outcomes[s.id]||t('تحسين أثر الجهة المثبت','Improve evidenced institutional impact'),outcome:t('رفع {kpi} من {baseline} إلى {target} {unit} بحلول {endYear}.','Raise {kpi} from {baseline} to {target} {unit} by {endYear}.'),whyUs:t('حدد القدرة المميزة ودليلها؛ هذا قالب مقترح.','Identify the distinctive capability and its evidence; this is a proposed template.'),tradeoff:t('تأجيل التوسع قبل إثبات النتيجة وتكلفة الاستدامة.','Defer expansion until outcomes and sustainable costs are evidenced.'),enablers:[{id:'decision',title:t('تحديد مالك القرار وصلاحيته','Identify the decision owner and authority'),kind:'authority',action:'activate',control:'unknown',owner:t('يُحدد','To be assigned'),source:t('وثيقة الصلاحية المطلوبة','Required authority document'),route:t('تحقق من الصلاحية قبل التنفيذ','Verify authority before execution'),fallback:t('تجربة محدودة ضمن الصلاحية المتاحة','A limited pilot within available authority')}],initiatives:[{id:'baseline',kind:'learn',start:0,end:0,title:t('توثيق خط الأساس واختبار الافتراضات','Establish the baseline and test assumptions'),output:t('قياس موثق وتعريف للمؤشر','Documented baseline and metric definition'),acceptance:t('مراجعة مصدر القياس ونطاقه','Review the measurement source and scope'),enablers:['decision'],dependsOn:[]},{id:'pilot',kind:'deliver',start:0,end:1,title:t('تجربة محدودة ومراجعة جدوى التوسع','Run a bounded pilot and review expansion'),output:t('نتائج قابلة للمقارنة وتكلفة موثقة','Comparable outcomes and documented cost'),acceptance:t('تحقق من النتيجة قبل التوسع','Verify outcomes before expansion'),enablers:['decision'],dependsOn:['baseline']}],assumptions:[],risk:t('قد لا ينطبق القياس أو المرجع على الدولة أو الفئة المختارة.','The measure or reference may not apply to the selected country or population.')}] }));
G.sector=id=>G.sectors.find(s=>s.id===id)||null;
G.goal=(sid,id)=>G.sector(sid)?.goals.find(x=>x.id===id)||null;
G.indicator=(sid,id)=>G.sector(sid)?.indicators.find(x=>x.id===id)||null;
G.reference=()=>null;G.program=()=>null;G.referencesFor=()=>[];
G.goalsFor=sid=>G.sector(sid)?.goals||[];
G.counts=sid=>({regulations:0,programs:0,indicators:G.sector(sid)?1:0,goals:G.sector(sid)?1:0});
G.detect=label=>{const s=L.detect(label);return s?G.sector(s.id):null;};
G.grounding=(sid,type,lang)=>{const s=G.sector(sid);return s?`General sector planning prompts, not verified regulations: ${L.pick(s.name,lang)}. Identify the actual country's regulators and applicable rules. No national programmes, published benchmark values or funding commitments are supplied.`:'';};
L.forMarket=market=>market==='global'?G:L;
root.SultanInternationalLibrary=G;
})(globalThis);
