(function(root){
'use strict';
const M=root.SultanMarket,A=root.SultanApp,T=(k,v)=>root.SultanI18n.t(k,v);
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const options=v=>['sa','global'].map(x=>`<option value="${x}" ${x===v?'selected':''}>${esc(T(x==='sa'?'mkSA':'mkGlobal'))}</option>`).join('');
function wizardFields(s){return `<div class="market-fields"><label class="field"><span>${esc(T('mkTitle'))}</span><select data-gw="market" data-market-wizard>${options(s.market)}</select></label><label class="field"><span>${esc(T('mkCountry'))}</span><input data-gw="country" maxlength="160" value="${esc(s.country)}"><small>${esc(T('mkCountryHelp'))}</small></label><label class="field"><span>${esc(T('mkCurrency'))}</span><input data-gw="currency" maxlength="3" pattern="[A-Z]{3}" value="${esc(s.currency)}" dir="ltr"><small>${esc(T('mkCurrencyHelp'))}</small></label></div><p class="market-note">${esc(T('mkNote'))}</p>`;}
function contextCard(p){const c=p.context;return `<details class="card market-settings"><summary>${esc(T('mkTitle'))}: ${esc(T(c.market==='global'?'mkGlobal':'mkSA'))} · <bdi>${esc(c.currency||T('mkUnknown'))}</bdi></summary><p>${esc(T('mkNote'))}</p><div class="market-fields"><label class="field"><span>${esc(T('mkTitle'))}</span><select id="market-project">${options(c.market)}</select></label><label class="field"><span>${esc(T('mkCountry'))}</span><input id="market-country" maxlength="160" value="${esc(c.country)}"></label><label class="field"><span>${esc(T('mkCurrency'))}</span><input id="market-currency" maxlength="3" pattern="[A-Z]{3}" value="${esc(c.currency)}" dir="ltr"></label></div><p>${esc(T('mkCurrencyHelp'))} ${esc(T('mkExisting'))}</p><button class="btn" type="button" data-market-save>${esc(T('mkSave'))}</button><p id="market-error" role="status"></p></details>`;}
function offlineState(){const state=root.SultanOffline?.state||'online';document.querySelectorAll('[data-co="offline"]').forEach(b=>{b.textContent=T({ready:'mkReady',preparing:'mkPreparing',error:'mkRetry'}[state]||'mkOnline');b.title=T('mkOfflineHelp');b.setAttribute('aria-label',b.textContent+'. '+T('mkOfflineHelp'));b.disabled=state==='preparing';});}
function apply(){const section=location.hash.slice(1)||'home',content=document.getElementById('content');if(!content)return;
 if(section==='home'&&!content.querySelector('.market-home')){const hero=content.querySelector('.hero-copy');hero?.insertAdjacentHTML('beforeend',`<label class="market-home"><span>${esc(T('mkTitle'))}</span><select data-market-home>${options(M.preferred())}</select><small>${esc(T('mkHint'))}</small></label>`);}
 if(['identity','strategy'].includes(section)&&!content.querySelector('.market-settings'))content.querySelector('.heading,.sw-header')?.insertAdjacentHTML('afterend',contextCard(A.getProject()));
 offlineState();
}
document.addEventListener('change',e=>{if(e.target.matches('[data-market-home]')){M.setPreferred(e.target.value);const u=new URL(location.href);u.searchParams.set('market',e.target.value);history.replaceState(null,'',u);A.navigate('home');}if(e.target.matches('[data-market-wizard]'))setTimeout(()=>A.navigate('guide'),0);});
document.addEventListener('click',e=>{if(!e.target.closest('[data-market-save]'))return;const p=A.getProject();const currency=document.getElementById('market-currency').value.trim().toUpperCase();if(!/^([A-Z]{3})?$/.test(currency)){document.getElementById('market-error').textContent=T('mkCurrencyHelp');return;}Object.assign(p.context,{market:document.getElementById('market-project').value,country:document.getElementById('market-country').value.trim(),currency});p.revision++;p.reviewedRevision=null;p.updatedAt=new Date().toISOString();A.setProject(p);});
document.addEventListener('sultan:render',()=>setTimeout(apply,0));document.addEventListener('sultan:offline',offlineState);
root.SultanMarketUI={wizardFields,apply};apply();
if(location.hash==='#guide')A.navigate('guide');
})(globalThis);
