/* Executive review visuals that keep strategic value, authority and money separate. */
(function(root){
'use strict';
const E=root.Sultan,T=root.SultanI18n.t,esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>typeof n==='number'&&Number.isFinite(n)?Math.round(n).toLocaleString('en-US'):'—';
function choiceCost(p,id){const ins=p.initiatives.filter(i=>i.optionId===id),known=ins.flatMap(i=>i.budget.filter(b=>typeof b.amount==='number'&&b.year>=i.startYear&&b.year<=i.endYear).map(b=>b.amount)),total=known.reduce((a,b)=>a+b,0),confirmed=ins.length>0&&ins.every(i=>i.budgetStatus==='confirmed');return {total,confirmed,count:ins.length};}
function render(){if(location.hash!=='#review'||!root.SultanApp)return;const content=document.getElementById('content');if(!content||content.querySelector('.portfolio-review'))return;const p=root.SultanApp.getProject(),selected=p.options.filter(o=>o.decision==='select'&&o.type!=='requirement'),authority=Object.fromEntries(E.authoritySpace(p).map(x=>[x.optionId,x])),rank=Object.fromEntries(E.ranking(p).map(x=>[x.id,x]));const card=document.createElement('article');card.className='card portfolio-review';const dots=selected.map((o,i)=>{const v=rank[o.id]?.value,a=authority[o.id]?.clearance;if(v===null||v===undefined||a===null||a===undefined)return '';return `<button type="button" class="matrix-dot" style="--x:${v};--y:${a}" title="${esc(o.title)} · ${Math.round(v)} / ${Math.round(a)}"><span>${i+1}</span></button>`;}).join('');card.innerHTML=`<h2>${esc(T('portfolioMatrix'))}</h2><p class="muted">${esc(T('portfolioMatrixHelp'))}</p><div class="matrix-wrap"><span class="matrix-y">${esc(T('authorityAxis'))}</span><div class="matrix"><i class="matrix-v"></i><i class="matrix-h"></i>${dots}</div><span class="matrix-x">${esc(T('strategicValue'))}</span></div><div class="matrix-legend">${selected.map((o,i)=>`<span><b>${i+1}</b> ${esc(o.title)}</span>`).join('')}</div><h2>${esc(T('valueFunding'))}</h2><div class="tablewrap"><table><thead><tr><th>${esc(T('authorityChoice'))}</th><th>${esc(T('strategicValue'))}</th><th>${esc(T('declaredInvestment'))}</th><th>${esc(T('fundingState'))}</th></tr></thead><tbody>${selected.map(o=>{const c=choiceCost(p,o.id),v=rank[o.id]?.value;return `<tr><td>${esc(o.title)}</td><td>${v==null?'—':Math.round(v)}</td><td>${money(c.total)} SAR</td><td>${esc(c.confirmed?T('fundingConfirmed'):T('fundingMixed'))}</td></tr>`;}).join('')}</tbody></table></div>`;const heading=content.querySelector('.heading');if(heading)heading.insertAdjacentElement('afterend',card);else content.prepend(card);}
document.addEventListener('sultan:render',()=>setTimeout(render,0));setTimeout(render,0);
})(globalThis);
