/* Executive review visuals that keep strategic value, authority and money separate. */
(function(root){
'use strict';
const E=root.Sultan,T=root.SultanI18n.t,esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>typeof n==='number'&&Number.isFinite(n)?Math.round(n).toLocaleString('en-US'):'—';
function choiceCost(p,id){const ins=p.initiatives.filter(i=>i.optionId===id);let total=0,unknown=0;for(const i of ins)for(const b of i.budget)if(b.year>=i.startYear&&b.year<=i.endYear){if(typeof b.amount==='number'&&Number.isFinite(b.amount))total+=b.amount;else unknown++;}const confirmed=ins.length>0&&ins.every(i=>i.budgetStatus==='confirmed');return {total,unknown,confirmed,count:ins.length};}
function render(){if(location.hash!=='#review'||!root.SultanApp)return;const content=document.getElementById('content');if(!content||content.querySelector('.portfolio-review'))return;const p=root.SultanApp.getProject(),selected=p.options.filter(o=>o.decision==='select'&&o.type!=='requirement'),authority=Object.fromEntries(E.authoritySpace(p).map(x=>[x.optionId,x])),rank=Object.fromEntries(E.ranking(p).map(x=>[x.id,x]));const card=document.createElement('article');card.className='card portfolio-review';const plotted=[],unplotted=[];selected.forEach((o,i)=>{const v=rank[o.id]?.value,a=authority[o.id]?.clearance;if(v==null||a==null)unplotted.push({o,i});else plotted.push({o,i,v,a});});const dots=plotted.map(({o,i,v,a})=>`<button type="button" class="matrix-dot" style="--x:${v};--y:${a}" title="${esc(o.title)} · ${Math.round(v)} / ${Math.round(a)}"><span>${i+1}</span></button>`).join('');const unknown=unplotted.length?`<div class="matrix-unplotted"><b>${esc(T('unplottedAuthority'))}</b>${unplotted.map(({o,i})=>`<span><b>${i+1}</b> ${esc(o.title)}</span>`).join('')}</div>`:'';card.innerHTML=`<h2>${esc(T('portfolioMatrix'))}</h2><p class="muted">${esc(T('portfolioMatrixHelp'))}</p><div class="matrix-wrap"><span class="matrix-y">${esc(T('authorityAxis'))}</span><div class="matrix"><i class="matrix-v"></i><i class="matrix-h"></i>${dots}</div><span class="matrix-x">${esc(T('strategicValue'))}</span></div>${unknown}<div class="matrix-legend">${selected.map((o,i)=>`<span><b>${i+1}</b> ${esc(o.title)}</span>`).join('')}</div><h2>${esc(T('valueFunding'))}</h2><div class="tablewrap"><table><thead><tr><th>${esc(T('authorityChoice'))}</th><th>${esc(T('strategicValue'))}</th><th>${esc(T('declaredInvestment'))}</th><th>${esc(T('fundingState'))}</th></tr></thead><tbody>${selected.map(o=>{const c=choiceCost(p,o.id),v=rank[o.id]?.value,amount=`${money(c.total)} ${esc(T('currencySAR'))}${c.unknown?` ${esc(T('unestimatedYears',[c.unknown]))}`:''}`;return `<tr><td>${esc(o.title)}</td><td>${v==null?'—':Math.round(v)}</td><td>${amount}</td><td>${esc(c.confirmed?T('fundingConfirmed'):T('fundingMixed'))}</td></tr>`;}).join('')}</tbody></table></div>`;const heading=content.querySelector('.heading');if(heading)heading.insertAdjacentElement('afterend',card);else content.prepend(card);}
document.addEventListener('sultan:render',()=>setTimeout(render,0));setTimeout(render,0);
})(globalThis);
