(function(root){
'use strict';
const S=root.SultanShare,esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let lang='ar',sequence=0,packet=null;
const T=k=>root.SultanLocales[lang]?.[k]||root.SultanLocales.en[k]||k;
const el=document.getElementById('share-content');
function fileButton(){return `<label>${esc(T('coReaderFile'))}<input id="share-file" type="file" accept=".json,application/json"></label>`;}
function home(){el.innerHTML=`<header><h1>${esc(T('coReader'))}</h1><p>${esc(T('coReaderHelp'))}</p></header>${fileButton()}<p id="share-status" role="status"></p>`;}
function pairs(rows){return `<dl>${rows.filter(([,v])=>v!==undefined&&v!==null&&v!=='').map(([k,v])=>`<dt><b>${esc(k)}</b></dt><dd>${esc(v)}</dd>`).join('')}</dl>`;}
function design(value){if(value===null)return esc(T('coUnknown'));if(Array.isArray(value))return value.map(x=>`<article>${design(x)}</article>`).join('');if(typeof value!=='object')return esc(value);return `<dl>${Object.entries(value).filter(([k])=>!['id','optionId','initiativeId','transitionId','version','enabled'].includes(k)).map(([k,v])=>{const key='swF_'+k,label=T(key)===key?k:T(key);return `<dt><b>${esc(label)}</b></dt><dd>${design(v)}</dd>`;}).join('')}</dl>`;}
function plan(p){return `<section class="share-block"><h2>${esc(p.institution?.name||'SULTAN')}</h2>${pairs([[T('s272'),p.institution?.mission],[T('s451'),p.institution?.vision],[T('s452'),p.institution?.notDoing]])}</section><h2>${esc(T('coBoardDecisions'))}</h2>${(p.options||[]).map(o=>`<article><h3>${esc(o.title)}</h3>${pairs([[T('s466'),o.decision],[T('s464'),o.whyUs],[T('s304'),o.tradeoff],[T('coOwner'),o.owner]])}<details><summary>${esc(T('coEvidence'))}</summary>${design(o.scores)}${design(o.assumptions||[])}</details></article>`).join('')}<h2>${esc(T('coBoardProgress'))}</h2>${(p.transitions||[]).map(t=>`<article><h3>${esc(t.kpi||t.domain)}</h3>${pairs([[T('coBaseline'),t.baseline??T('coUnknown')],[T('coTarget'),(t.direction==='delta'?(typeof t.baseline==='number'&&typeof t.target==='number'?t.baseline+t.target:null):t.target)??T('coUnknown')],[T('coEvidence'),t.currentSource],[T('coOwner'),t.owner]])}<details><summary>${esc(T('coBoardDetails'))}</summary>${design(t)}</details></article>`).join('')}<details class="share-block"><summary>${esc(T('coBoardAuthority'))}</summary>${design(p.enablers||[])}</details><details class="share-block"><summary>${esc(T('coBoardTimeline'))}</summary>${design(p.initiatives||[])}</details><details class="share-block"><summary>${esc(T('coBoardFunding'))}</summary>${design(p.funding||[])}</details><details class="share-block"><summary>${esc(T('coEvidence'))}</summary>${design(p.references||[])}${design(p.context?.sources||[])}</details><details class="share-block"><summary>${esc(T('swNav'))}</summary>${design(p.strategy||{})}</details>`;}
async function open(value){const seq=++sequence;packet=null;home();try{const result=await S.read(value);if(seq!==sequence)return;const p=result.payload;lang=p.language==='en'?'en':'ar';document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';packet=result.packet;if(p.kind==='response'){el.innerHTML=`<h1>${esc(T('coReturnReply'))}</h1><textarea class="share-response-link" readonly id="share-return-link">${esc(S.link(await S.encode(packet),'r'))}</textarea>${fileButton()}`;return;}if(!p.snapshot?.institution||!Array.isArray(p.snapshot.options))throw Error(T('coInvalid'));el.innerHTML=`<header><h1>${esc(T('coReader'))}</h1>${p.isDemo?`<p>${esc(T('fictional'))}</p>`:''}<p>${esc(T('coShareLimits'))}</p><p>${esc(T('coFingerprint'))}: <bdi>${esc(result.fingerprint)}</bdi></p><time>${esc(p.createdAt)}</time> — <time>${esc(p.expiresAt)}</time></header>${plan(p.snapshot)}${p.kind==='invite'?`<section class="share-block"><h2>${esc(T('coOwner'))}: ${esc(p.owner)}</h2><p>${esc(T('coOwnerPosition'))}</p><form id="share-reply-form"><label>${esc(T('coOwnerPosition'))}<select id="share-stance">${[['support','coSupport'],['changes','coChanges'],['abstain','coAbstain']].map(([v,k])=>`<option value="${v}">${esc(T(k))}</option>`).join('')}</select></label><label>${esc(T('coReplyComment'))}<textarea id="share-comment" maxlength="4000" required></textarea></label><button class="btn" type="submit">${esc(T('coSendReply'))}</button></form><div id="share-response"></div></section>`:''}${fileButton()}<p id="share-status" role="status"></p>`;}catch(e){home();document.getElementById('share-status').textContent=T('coError')+e.message;}}
document.addEventListener('change',async e=>{if(e.target.id!=='share-file')return;const f=e.target.files[0];if(!f)return;try{if(f.size>S.MAX*2)throw Error(T('coLimit'));await open(await S.encode(JSON.parse(await f.text())));}catch(err){document.getElementById('share-status').textContent=T('coError')+err.message;}});
document.addEventListener('submit',async e=>{if(e.target.id!=='share-reply-form')return;e.preventDefault();try{const response=await S.reply(packet,document.getElementById('share-stance').value,document.getElementById('share-comment').value),token=await S.encode(response),url=token.length<=S.LINK_MAX?S.link(token,'r'):'';const data=URL.createObjectURL(new Blob([JSON.stringify(response)],{type:'application/json'}));document.getElementById('share-response').innerHTML=`<p>${esc(T('coReturnReply'))}</p>${url?`<textarea id="share-return-link" class="share-response-link" readonly>${esc(url)}</textarea>`:`<p>${esc(T('coLargeLink'))}</p>`}<a class="btn" href="${data}" download="SULTAN_signed_response.json">${esc(T('coSignedFile'))}</a>`;setTimeout(()=>URL.revokeObjectURL(data),600000);}catch(err){document.getElementById('share-status').textContent=T('coError')+err.message;}});
addEventListener('hashchange',()=>location.hash?open(location.hash):home());if(location.hash)open(location.hash);else home();
})(globalThis);
