/* Signed local snapshots. Possession is a capability, never verified identity. */
(function(root){
'use strict';
const MAX=240000,LINK_MAX=24000,enc=new TextEncoder(),dec=new TextDecoder();
const stable=x=>Array.isArray(x)?x.map(stable):x&&typeof x==='object'?Object.fromEntries(Object.keys(x).sort().map(k=>[k,stable(x[k])])):x;
const canonical=x=>JSON.stringify(stable(x));
const b64=b=>{let s='';for(const n of new Uint8Array(b))s+=String.fromCharCode(n);return btoa(s).replaceAll('+','-').replaceAll('/','_').replace(/=+$/,'');};
function un64(s){if(typeof s!=='string'||s.length>MAX*2||!/^[-\w]+$/.test(s))throw Error('Invalid encoding');return Uint8Array.from(atob(s.replaceAll('-','+').replaceAll('_','/')),c=>c.charCodeAt(0));}
function safe(x,depth=0){if(depth>24)throw Error('Snapshot nesting limit');if(x&&typeof x==='object')for(const k of Object.keys(x)){if(['__proto__','prototype','constructor'].includes(k))throw Error('Unsafe key');safe(x[k],depth+1);}}
async function digest(x){return b64(await crypto.subtle.digest('SHA-256',enc.encode(canonical(x))));}
async function keys(){const p=await crypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},true,['sign','verify']);return {privateKey:await crypto.subtle.exportKey('jwk',p.privateKey),publicKey:await crypto.subtle.exportKey('jwk',p.publicKey)};}
async function issuer(){let saved;try{saved=JSON.parse(localStorage.getItem('sultan.share.signer.v1')||'null');}catch{}if(saved?.privateKey&&saved?.publicKey)return saved;const p=await keys();localStorage.setItem('sultan.share.signer.v1',JSON.stringify(p));return p;}
async function sign(payload,pair){const key=await crypto.subtle.importKey('jwk',pair.privateKey,{name:'ECDSA',namedCurve:'P-256'},false,['sign']);return {payload,publicKey:pair.publicKey,signature:b64(await crypto.subtle.sign({name:'ECDSA',hash:'SHA-256'},key,enc.encode(canonical(payload))))};}
async function verify(packet,expected){safe(packet);if(!packet?.payload||!packet.publicKey||!packet.signature||packet.publicKey.d)throw Error('Invalid snapshot');if(expected&&canonical(packet.publicKey)!==canonical(expected))throw Error('Unexpected reply key');const key=await crypto.subtle.importKey('jwk',packet.publicKey,{name:'ECDSA',namedCurve:'P-256'},false,['verify']);if(!await crypto.subtle.verify({name:'ECDSA',hash:'SHA-256'},key,un64(packet.signature),enc.encode(canonical(packet.payload))))throw Error('Signature mismatch');return packet.payload;}
async function encode(packet){const data=enc.encode(canonical(packet));if(data.length>MAX)throw Error('Snapshot too large');if(typeof CompressionStream==='undefined')return 'j.'+b64(data);return 'g.'+b64(await new Response(new Blob([data]).stream().pipeThrough(new CompressionStream('gzip'))).arrayBuffer());}
async function decode(value){const token=String(value||'').split('#').at(-1).replace(/^[sr]=/,'').trim();if(token.length>MAX*2)throw Error('Snapshot too large');const [kind,data]=token.split('.');let bytes=un64(data);if(kind==='g'){const reader=new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip')).getReader();let n=0,parts=[];for(;;){const {value,done}=await reader.read();if(done)break;n+=value.length;if(n>MAX){await reader.cancel();throw Error('Snapshot too large');}parts.push(value);}bytes=new Uint8Array(n);let offset=0;for(const p of parts){bytes.set(p,offset);offset+=p.length;}}else if(kind!=='j')throw Error('Unknown format');if(bytes.length>MAX)throw Error('Snapshot too large');const packet=JSON.parse(dec.decode(bytes));safe(packet);return packet;}
const unexpired=p=>p.expiresAt&&Number.isFinite(Date.parse(p.expiresAt))&&Date.parse(p.expiresAt)>=Date.now();
async function read(value){const packet=await decode(value),p=await verify(packet);if(p.version!==1||!['read','invite','response'].includes(p.kind))throw Error('Unsupported snapshot');if(p.kind!=='response'&&!unexpired(p))throw Error('Link expired');return {packet,payload:p,fingerprint:(await digest(packet.publicKey)).slice(0,16)};}
function link(token,type='s'){if(token.length>LINK_MAX)throw Error('Link too large; use signed file');return new URL('share.html',location.protocol==='file:'?'https://sultan-strategy-beta.onrender.com/':location.href).href.split('#')[0]+'#'+type+'='+token;}
async function reply(packet,stance,comment){const p=await verify(packet);if(p.kind!=='invite'||!unexpired(p)||!['support','changes','abstain'].includes(stance)||typeof comment!=='string'||!comment.trim()||comment.length>4000)throw Error('Invalid response');const pair={privateKey:packet.replyKey,publicKey:p.replyPublic};if(!pair.privateKey||pair.privateKey.x!==p.replyPublic.x||pair.privateKey.y!==p.replyPublic.y)throw Error('Invalid capability');return sign({version:1,kind:'response',requestId:p.id,basis:p.basis,owner:p.owner,stance,comment:comment.trim(),at:new Date().toISOString()},pair);}
root.SultanShare={canonical,digest,keys,issuer,sign,verify,encode,decode,read,link,reply,MAX,LINK_MAX};
})(globalThis);
